---
title: "Capítulo 1 - Repaso"
author: "Daniel Czarnievicz"
date: "2019"
output: pdf_document
header-includes:
   - \everymath{\displaystyle}
geometry: margin=1in
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Espacio de probabilidad

## $\sigma$-álgebras

#### Definición 1.1:

Dado un conjunto $\Omega \neq \emptyset$, diremos que $\mathcal{A} \subset 2^{\Omega}$ es una $\sigma$-álgebra de subconjuntos de $\Omega$ si se cumple que:

1. $\Omega \in \mathcal{A}$  
2. si $A \in \mathcal{A} \Rightarrow A^c \in \mathcal{A}$  
3. si $\{ A_n \}_{n \in \mathbb{N}} \in \mathcal{A} \Rightarrow \bigcup\limits_{n \in \mathbb{N}} A_n \in \mathcal{A}$

#### Proposición 1.2: 

Si $\mathcal{A}$ es una $\sigma$-álgebra, entonces:

***

1. $\emptyset \in \mathcal{A}$

*Dem*: $\Omega^c = \emptyset$, luego entonces, por axioma 2, $\emptyset \in \mathcal{A}$, dado que $\Omega \in \mathcal{A}$ por axima 1.

***

2. Si $A_1; \, \ldots; \, A_n \in \mathcal{A} \Rightarrow \bigcup\limits_{i = 1}^{n} A_i \in \mathcal{A}$

*Dem*: por el aximoma 3 sabemos que la unión infinito-numerable pertenece a la $\sigma$-álgebra. Definimos la sucesión de conjuntos $\{ B_n \}_{n \in \mathbb{N}}$ tal que: $B_1 = A_1; \, B_2 = A_2; \, \ldots; \, B_n = A_n; B_{n+1} = \emptyset; B_{n+2} = \emptyset; \, \ldots$, luego entonces:

$$ \bigcup\limits_{i=1}^{n} A_i = \bigcup\limits_{i=1}^{+\infty} B_i \in \mathcal{A} \Rightarrow \bigcup\limits_{i=1}^{n} A_i \in \mathcal{A} $$

3. Si $\{ A_n \}_{n \in \mathbb{N}} \subset \mathcal{A} \Rightarrow \bigcap\limits_{i = 1}^{+\infty} A_i \in \mathcal{A}$

*Dem*: si $A_i \in \mathcal{A} \Rightarrow$ por el axioma 2, $A_i^c \in \mathcal{A} \Rightarrow$ por el axioma 3, $\bigcup_{i = 1}^{+ \infty} A_i^c \in \mathcal{A} \Rightarrow$

$\Rightarrow$ por el axioma 2, $\left( \bigcup_{i = 1}^{+ \infty} A_i^c \right)^c \in \mathcal{A} \Rightarrow$ por De Morgan, $\bigcap_{i = 1}^{+ \infty} (A_i^c)^c \in \mathcal{A} \Rightarrow \bigcap_{i = 1}^{+ \infty} A_i \in \mathcal{A}$

***

4. Si $A,B \in \mathcal{A} \Rightarrow A - B \in \mathcal{A}$

*Dem*: $A \in \mathcal{A}$ por hipótesis. $B \in \mathcal{A}$ por hipótesis $\Rightarrow B^c \in \mathcal{A}$ por el axioma 2. Luego, $A - B = A \cap B^c = \big( A^c \cup (B^c)^c \big)^c \in \mathcal{A}$.

***

5. Si $\mathcal{A}_{\alpha}$ es una $\sigma$-álgebra de conjuntos sobre $\Omega$ para todo $\alpha \in I$, siendo $I$ un conjunto cualquiera de índices, entonces $\bigcap\limits_{\alpha \in I} \mathcal{A}_{\alpha}$ es $\sigma$-álgebra de conjuntos sobre $\Omega$. 

*Dem*: requiere probar cada uno de los tres axiomas.

\vspace{0.1cm}

Axioma 1: por hipótesis, $\mathcal{A}_{\alpha}$ es $\sigma$-álgebra $\forall \alpha \in I \Rightarrow$ por axioma 1, $\Omega \in \mathcal{A}_{\alpha} \forall \alpha \in I \Rightarrow$ por definición de intersección, $\Omega \in \bigcap\limits_{\alpha \in I} \mathcal{A}_{\alpha}$.

Axioma 2: si $A \in \bigcap\limits_{\alpha \in I} \mathcal{A}_{\alpha} \Rightarrow$ por definición de intersección, $A \in \mathcal{A}_{\alpha} \forall \alpha \in I$. A su vez, si $A \in \mathcal{A}_{\alpha} \forall \alpha \in I \Rightarrow$ por axioma 2, $A^c \in \mathcal{A}_{\alpha} \forall \alpha \in I \Rightarrow$ por definición de intersección, $A^c \in \bigcap\limits_{\alpha \in I} \mathcal{A}_{\alpha}$.

Axioma 3: si $\{A_n\}_{n \in \mathbb{N}} \in \bigcap\limits_{\alpha \in I} \mathcal{A}_{\alpha} \Rightarrow$ por definición de intersección, $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}_{\alpha} \forall \alpha \in I$. Luego, si $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}_{\alpha} \forall \alpha \in I \Rightarrow$ por definición de unión, $\{A_n\}_{n \in \mathbb{N}} \in \bigcup\limits_{\alpha \in I} \mathcal{A}_{\alpha}$.

***

#### Definición 1.4:

Dada una familia $\mathcal{F}$ de subconjuntos de $\Omega$, el conjunto $\bigcap\limits_{\mathcal{A}: \mathcal{F} \subset \mathcal{A}} \mathcal{A}$ (es decir, la intersección de todas las $\sigma$-álgebras que contienen a la familia de subconjuntos $\mathcal{F}$), se llama $\sigma$-álgebra generada por $\mathcal{F}$, y se denota por $\sigma(\mathcal{F})$.

#### Definición 1.5:

La $\sigma$-álgebra de Borel en $\mathbb{R}$ es $\sigma(\mathcal{F})$ con $\mathcal{F} = \{ A \subset \mathbb{R} / A \text{ es abierto} \}$.

\newpage

#### Proposición 1.6

Sea $f : \Omega \rightarrow \Omega'$ y $\mathcal{D}$ una familia de subconjuntos de $\Omega'$, entonces $\sigma \big( f^{-1} ( \mathcal{D} ) \big) = f^{-1} \big( \sigma ( \mathcal{D} ) \big)$, donde denotamos, para $B \in \mathcal{D}$, $f^{-1}(B) = \{ \omega \in \Omega / f(\omega) \in B \}$ la pre-imagen de $B$ por $f$.

*Dem*:

#### Teorema 1.7

La $\sigma$-álgebra de Borel puede ser generada por cualquiera de los siguientes conjuntos:

1. $I_1 = \big\{ (a,b) \subset \mathbb{R} / a < b \big\}$
2. $I_2 = \big\{ [a,b) \subset \mathbb{R} / a < b \big\}$
3. $I_3 = \big\{ (a,b] \subset \mathbb{R} / a < b \big\}$
4. $I_4 = \big\{ (a,+\infty) \subset \mathbb{R} / a \in \mathbb{R} \big\}$
5. $I_5 = \big\{ [a,+\infty) \subset \mathbb{R} / a \in \mathbb{R} \big\}$
6. $I_6 = \big\{ (-\infty,b) \subset \mathbb{R} / b \in \mathbb{R} \big\}$
7. $I_7 = \big\{ (-\infty,b] \subset \mathbb{R} / b \in \mathbb{R} \big\}$

*Dem*: $I_1$ es inmediato dado que $(a,b)$ es un conjunto abierto, por lo tanto, el conjunto de los abiertos engendra la $\sigma$-álgebra de Borel en $\mathbb{R}$ por dado que así es como está definida la misma. 

Para el resto de los conjuntos solo debemos demostrar que los mismos pueden ser escritos como la unión infinita de conjuntos abiertos (la cual es abierta), y por tanto engendran el set de Borel.

- $I_2 = [a,b) = \{a\} \cup (a,b) = \left\{ \bigcap\limits_{n \in \mathbb{N}} B(a, \, ^1\!/_n) \right\} \cup (a,b)$

- $I_3 = (a,b] = (a,b) \cup \{b\} = (a,b) \cup \left\{ \bigcap\limits_{n \in \mathbb{N}} B(b, \, ^1\!/_n) \right\}$

- $I_4 = (a,+\infty) = \bigcup\limits_{n \in \mathbb{N}} (a, \, n)$

- $I_5 = [a, +\infty) = \{a\} \cup (a, +\infty) = \{a\} \cup \left\{ \bigcup\limits_{n \in \mathbb{N}} (a, \, n) \right\}$

- $I_6 = (-\infty, b) = \left\{ \bigcup\limits_{n \in \mathbb{N}} (-n, \, b) \right\}$

- $I_7 = (-\infty, b] = (-\infty, b) \cup \{b\} = \left\{ \bigcup\limits_{n \in \mathbb{N}} (-n, \, b) \right\} \cup \{b\}$

## Espacio de probabilidad

#### Definición 1.8

Dado $\Omega \neq \emptyset$, diremos que la terna $(\Omega, \, \mathcal{A}, \, P)$ es un espacio de probabilidad sobre $\Omega \Leftrightarrow \mathcal{A}$ es una $\sigma$-álgebra de conjuntos sobre $\Omega$ y $P$ es una función $P: \mathcal{A} \rightarrow [0;1]$ que cumple:

i. $P(\Omega) = 1$
ii. si la familia de sucesos $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}$ son tales que $A_i \cap A_j = \emptyset \, \forall i \neq j$ (disjuntos dos a dos), entonces:
$$ P \left( \bigcup\limits_{n = 1}^{+ \infty} A_n \right) = \sum\limits_{n = 1}^{+\infty} P(A_n) $$

#### Proposición 1.9

***

1) $P(\emptyset) = 0$

*Dem*: $P(\Omega) = P(\Omega \cup \emptyset) \Rightarrow$ por ser $\Omega$ y $\emptyset$ conjuntos disjuntos, $P(\Omega) = P(\Omega) + P(\emptyset) \Rightarrow$ por prop 1.9/2 (ver abajo), $1 = 1 + P(\emptyset) \Rightarrow 0 = P(\emptyset)$

*Dem*: sea la sucesión $B_n$ tal que $B_1 = \emptyset$, $B_2 = \emptyset$, $B_3 = \emptyset$, $\ldots$. Luego entonces,
$$\begin{array}{c c c}
P \left( \bigcup\limits_{i = 1}^{+\infty} B_i \right) = \sum\limits_{i = 1}^{+\infty} P(B_i) & & \text{por ser la probabilidad de una sucesión contable} \\ \\
\sum\limits_{i = 1}^{+\infty} P(B_i) = 0 & & \text{dado que la serie del mismo número positivo solo} \\
& & \text{puede converger a $0$ (si es cero) o diverger, pero las} \\ 
& & \text{probabilidades deben estar acotadas entre 1 y 0} \\
\end{array}$$

***

2) Sea $A_1; \, \ldots; \, A_n \in \mathcal{A} / A_i \cap A_j = \emptyset \, \forall i \neq j \Rightarrow P \left( \bigcup\limits_{i = 1}^{n} A_i \right) = \sum\limits_{i = 1}^{n} P(A_i)$

*Dem*: consideremos la suceción de eventos $B_1 = A_1; \, B_2 = A_2; \, \ldots; \, B_n = A_n; B_{n+1} = \emptyset; \, \ldots$ luego entonces:

$$\begin{array}{ c c c} 
P \left( \bigcup\limits_{i = 1}^{n} A_i \right) = P \left( \bigcup\limits_{i = 1}^{+\infty} B_i \right) & & \text{debido a que la diferencia entre la sucesión $A_n$ y la} \\
& & \text{$B_n$ son infinitos conjuntos vacios.} \\ \\
P \left( \bigcup\limits_{i = 1}^{+\infty} B_i \right) = \sum\limits_{i = 1}^{+\infty} P(B_i) & & \text{por axioma ii.} \\ \\
\sum\limits_{i = 1}^{+\infty} P(B_i) = \sum\limits_{i = 1}^{n} P(B_i) + \sum\limits_{i = n+1}^{+\infty} P(B_i) & & \text{por linealidad de la suma} 
\end{array}$$

$$\begin{array}{c c c}
\sum\limits_{i = 1}^{+\infty} P(B_i) = \sum\limits_{i = 1}^{n} P(A_i) + \sum\limits_{i = n+1}^{+\infty} P(B_i) & & \text{por la definición de la sucesión $B_n$} \\ \\
\sum\limits_{i = 1}^{n} P(A_i) + \sum\limits_{i = n+1}^{+\infty} P(B_i) = \sum\limits_{i = 1}^{n} P(A_i) + \sum\limits_{i = n+1}^{+\infty} 0 & & \text{porque $P(\emptyset) = 0$}
\end{array}$$

Uniendo las puntas llegamos a que:

$$P \left( \bigcup\limits_{i = 1}^{n} A_i \right) = \sum\limits_{i = 1}^{n} P(A_i)$$

***

3) Si $A,B \in \mathcal{A} \Rightarrow P(B - A) = P(B) - P(A \cap B)$

*Dem*:

$$\begin{array}{ c c c} 
B = B & & \text{tautología} \\ \\
(B - A) \cup (A \cap B) = B & & \text{por definición de diferencia} \\ \\
P \big( (B-A) \cup (A \cap B) \big) = P(B) & & \text{tomo probabilidades} \\ \\
P (B-A) + P (A \cap B) = P(B) & & \text{sucesos disjuntos} \\ \\
P (B-A) = P(B) - P (A \cap B) & & 
\end{array}$$

***

4) Sean $A,B \in \mathcal{A} / A \subset B \Rightarrow P(B - A) = P(B) - P(A)$ y $P(A) \leq P(B)$ 

*Dem*: primer enunciado: sean $A,B \in \mathcal{A} / A \subset B \Rightarrow P(B - A) = P(B) - P(A)$

$$\begin{array}{ c c c } 
B = B & & \text{tautología} \\ \\
(B - A) \cup (A \cap B) = B & & \text{por definición de diferencia} \\ \\
(B - A) \cup A = B & & \text{por inclusión de $A$ en $B$} \\ \\
P \big( (B-A) \cup A \big) = P(B) & & \text{tomo probabilidades} \\ \\
P (B-A) + P (A) = P(B) & & \text{sucesos disjuntos} \\ \\
P (B-A) = P(B) - P (A) & & 
\end{array}$$

*Dem*: segundo enunciado: sean $A,B \in \mathcal{A} / A \subset B \Rightarrow P(A) \leq P(B)$

$$\begin{array}{ c c c} 
B = A \cup (B - A) & & \text{dado que $A \subset B$} \\ \\
P(B) = P \big( A \cup (B - A) \big) & & \text{tomando probabilidades de ambos lados} \\ \\
P(B) = P(A) + P(B - A) & & \text{dado que $A$ y $B-A$ son disjuntos por la inclusión} \\ \\
\end{array}$$

Por lo tanto, $P(B) = P(A) + P(B - A) \geq P(A)$ dado que $P(B - A) \geq 0$, de donde obtenemos que $P(A) \leq P(B)$.

***

5) Sean $A,B \in \mathcal{A} \Rightarrow P(A \cup B) = P(A) + P(B) - P(A \cap B)$

*Dem*:

$$\begin{array}{c c c}
\left\{ \begin{array}{c c c}
A & = & (A - B) \cup (A \cap B) \\
B & = & (B - A) \cup (A \cap B)
\end{array} \right.
& & \text{por definición de diferencia} \\ \\
\left\{ \begin{array}{c c c}
P(A) & = & P \big( (A - B) \cup (A \cap B) \big) \\
P(B) & = & P \big( (B - A) \cup (A \cap B) \big)
\end{array} \right.
& & \text{tomo probabilidades} \\ \\
\left\{ \begin{array}{c c c}
P(A) & = & P(A - B) + P(A \cap B) \\
P(B) & = & P(B - A) + P(A \cap B)
\end{array} \right.
& & \text{por ser sucesos disjuntos} \\ \\
P(A) + P(B) = P(A-B) + P(B-A) + 2 P(A \cap B) & & \text{sumo de ambos lados} \\ \\
P(A) + P(B) - P(A \cap B) = P(A - B) + P(B - A) + P(A \cap B) & & \text{reordeno términos} \\ \\
P(A) + P(B) - P(A \cap B) = P \big((A - B) \cup (B - A) \cup (A \cap B) \big) & & \text{sucesos disjuntos} \\ \\
P(A) + P(B) - P(A \cap B) = P (A \cup B) & & 
\end{array}$$

***

6) Si $A_!; \, \ldots; \, A_n \in \mathcal{A} \Rightarrow P \left( \bigcup\limits_{i = 1}^{n} A_i \right) \leq \sum\limits_{i = 1}^{n} P(A_i)$

*Dem*: en la parte 5) de la proposición se demostró que $P(A \cup B) = P(A) + P(B) - P(A\cap B)$. Dado que $P(A\cap B) \geq 0$, esto implica que $P(A \cup B) \leq P(A) + P(B)$.

Siguiendo un procedimiento análogo podemos demostrar, para $n = 3$, que:
$$P(A \cup B \cup C) = P(A) + P(B) - P(A \cap B) + P(C) - P(A \cap C) - P(B \cap C) + P(A \cap B \cap C) \Rightarrow$$
$$\Rightarrow P(A \cup B \cup C) = P(A) + P(B) + P(C) - \big[ P(A \cap B) + P(A \cap C) + P(B \cap C) \big] + P(A \cap B \cap C) $$
donde $P(A_i \cap A_j) \geq P(A_i \cap A_j \cap A_k)$ para cualquier par y terna de conjuntos, dado que del lado izquierdo estamos intersectando más conjuntos, es decir, excluyendo más sucesos. De donde obtenemos que $P(A \cup B \cup C) \leq P(A) + P(B) + P(C)$.

Si continuamos con este proceso hasta llegar a $n$ sucesos, encontramos que:
$$ P \left( \bigcup\limits_{k = 1}^{n} A_k \right) = \sum\limits_{k = 1}^{n} P(A_k) - \sum\limits_{\substack{i_1, i_2 = 1 \\ i_1 < i_2}}^{n} P(A_{i_1} \cap A_{i_2}) + \sum\limits_{\substack{i_1, i_2. i_3 = 1 \\ i_1 < i_2 < i_3 }}^{n} P(A_{i_1} \cap A_{i_2} \cap A_{i_3}) + $$
$$ + \ldots + (-1)^{k-1} \sum\limits_{\substack{i_1. \ldots, i_k = 1 \\ i_1 < \ldots < i_k }}^{n} P(A_{i_1} \cap \ldots \cap A_{i_k}) + \ldots + (-1)^{n-1} P(A_{i_1} \cap \ldots \cap A_{i_n}) $$
donde $P(A_{i_1} \cap A_{i_2}) \geq P(A_{i_1} \cap A_{i_2} \cap A_{i_3}) \geq P(A_{i_1} \cap A_{i_2} \cap A_{i_3} \cap A_{i_4}) \geq \ldots$ para cualquier comparación de $n$-úplas de conjuntos. De donde obtenemos que:
$$P \left( \bigcup\limits_{i = 1}^{n} A_i \right) \leq \sum\limits_{i = 1}^{n} P(A_i)$$

***

7) si $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}$ es tal que $A_1 \subset A_2 \subset A_3 \subset \ldots$, entonces $P \left( \bigcup\limits_{n \in \mathbb{N}} A_n \right) = \lim\limits_{n \rightarrow +\infty} P(A_n)$

*Dem*: comenzamos definiendo la siguiente sucesión de conjuntos disjuntos:
$$B_1 = A_1; \, B_2 = A_2 - A_1; \, B_3 = A_3 - A_2; \ldots; \, B_n = A_n - A_{n-1}; \ldots$$

Nótese que no es necesario unir los conjuntos de índices menores a $n$ a la hora de definir $B_n$ dado que la sucesión $\{A_n\}_{n \in \mathbb{N}}$ es creciente. Esto último implica que, al restar $A_{n-1}$ a $A_n$, ya estamos exluyendo a los elementos de los conjuntos $A_{n-2}; \, A_{n-3}; \ldots; \, A_3; \, A_2; \, A_1$. Por lo tanto, la sucesión $\{B_n\}_{n \in \mathbb{N}}$ es una sucesión de conjuntos disjuntos.

$$\begin{array}{ c c c } 
\bigcup\limits_{n \in \mathbb{N}} A_n = \bigcup\limits_{n \in \mathbb{N}} B_n & & \text{por definición de $B_n$} \\ \\
P \left( \bigcup\limits_{n \in \mathbb{N}} A_n \right) = P \left( \bigcup\limits_{n \in \mathbb{N}} B_n \right) & & \text{dado que $\{A_n\}_{n \in \mathbb{N}}$ y $\{B_n\}_{n \in \mathbb{N}}$} \\
& & \text{están definidas sobre el mismo $(\Omega, \mathcal{A}, P)$} \\ \\
P \left( \bigcup\limits_{n \in \mathbb{N}} B_n \right) = \sum\limits_{n = 1}^{+\infty} P(B_n) & & \text{por el axioma ii.} \\ \\
\sum\limits_{n = 1}^{+\infty} P(B_n) = P(B_1) + \sum\limits_{n = 2}^{+\infty} P(B_n) & & \text{reordeno términos}
\end{array}$$

Continuando con la segunda igualdad, ahora solo resta desarmar la sucesión $\{B_n\}_{n \in \mathbb{N}}$ en términos de los sucesos $A_n$ y calcular la serie.

$$\begin{array}{ c c c } 
P(B_1) + \sum\limits_{n = 2}^{+\infty} P(B_n) = & & \text{} \\ \\
= P(A_1) + \sum\limits_{n = 2}^{+\infty} P(A_n - A_{n-1}) = & & \text{re-escribo $B_n$ en términos de $A_n$} \\ \\
= P(A_1) + \sum\limits_{n = 2}^{+\infty} \big[ P (A_n)  - P(A_{n-1}) \big] = & & \text{reordeno términos} \\ \\
= P(A_1) + \lim_{m \rightarrow +\infty} \sum\limits_{n = 2}^{m} \big[ P (A_n) - P(A_{n-1}) \big] = & & \text{resuelvo la serie como el límite de} \\
& & \text{sus sumas parciales} \\ \\
= P(A_1) + \lim_{m \rightarrow +\infty} \big[ P (A_m) - P(A_1) \big] & & \text{por ser una serie telescópica} \\ \\
= P(A_1) + \lim_{m \rightarrow +\infty} P (A_m) - P(A_1) & & \\ \\
= \lim\limits_{m \rightarrow +\infty} P(A_m)
\end{array}$$

***

8) si $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}$ es tal que $A_1 \supset A_2 \supset A_3 \supset \ldots$, entonces $P \left( \bigcap\limits_{n \in \mathbb{N}} A_n \right) = \lim\limits_{n \rightarrow +\infty} P(A_n)$

*Dem*: nótese que si $A_1 \supset A_2 \supset A_3 \supset \ldots \Rightarrow A_1^c \subset A_2^c \subset A_3^c \subset \ldots$. Luego dado que $\{A_n\}_{n \in \mathbb{N}}$ es una sucesión decreciente, $\{A_n^c\}_{n \in \mathbb{N}}$ es una sucesión creciente, por lo tanto, estamos en las hipótesis de la proposición anterior. Por lo tanto,

$$\begin{array}{c c c}
P \left( \bigcup\limits_{n \in \mathbb{N}} A_n^c \right) = \lim\limits_n P(A_n^c) & & \text{por prop. 1.9/7} \\ \\
P \left[ \left( \bigcap\limits_{n \in \mathbb{N}} A_n \right)^c \right] = \lim\limits_n P(A_n^c) & & \text{por De Morgan} \\ \\
1 - P \left( \bigcap\limits_{n \in \mathbb{N}} A_n \right) = \lim\limits_n \left[ 1 - P(A_n) \right] & & \text{por probabilidad del complemento} \\ \\
1 - P \left( \bigcap\limits_{n \in \mathbb{N}} A_n \right) = 1 - \lim\limits_n P(A_n) & & \text{por linealidad del límite}
\end{array}$$
\noindent
$$\begin{array}{c c c}
\lim\limits_n P(A_n) = P \left( \bigcap\limits_{n \in \mathbb{N}} A_n \right) & &
\end{array}$$

***

9) si $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}$ es tal que $P(A_n) = 1 \,\, \forall n \in \mathbb{N}$, entonces $P \left( \bigcap\limits_{n \in \mathbb{N}} A_n \right) = 1$

*Dem*: si $P(A_n) = 1 \Rightarrow P(A^c_n) = 1 - P(A_n) = 0$, luego entonces:

$$\begin{array}{c c c}
P \left( \bigcap\limits_{n = 1}^{+\infty} A_n \right) = P \left[ \left( \bigcup\limits_{n = 1}^{+\infty} A_n^c \right)^c \right] & & \text{por De Morgan} \\ \\
P \left[ \left( \bigcup\limits_{n = 1}^{+\infty} A_n^c \right)^c \right] = 1 - P \left( \bigcup\limits_{n = 1}^{+\infty} A_n^c \right) & & \text{por probabilidad del complemento}
\end{array}$$

Luego, $0 \leq P \left( \bigcup\limits_{n = 1}^{+\infty} A_n^c \right) \leq \sum\limits_{n = 1}^{+\infty} P(A_n^c) = 0$ por ser la suma de conjuntos de probabilidad cero. Por lo tanto, $P \left( \bigcup\limits_{n = 1}^{+\infty} A_n^c \right) = 0$, dado que está acotado inferior y superiormente por cero. Esto implica que:
$$P \left( \bigcap\limits_{n = 1}^{+\infty} A_n \right) = P \left[ \left( \bigcup\limits_{n = 1}^{+\infty} A_n^c \right)^c \right] = 1 - P \left( \bigcup\limits_{n = 1}^{+\infty} A_n^c \right) \geq 1$$

Lo cual implica que: $P \left( \bigcap\limits_{n = 1}^{+\infty} A_n \right) = 1$ dado que está acotado superiormente por 1 por ser una probabilidad.

## Límite superior e inferior

#### Definición: límite superior e inferior de una sucesión

Sea $\{a_n\}_{n \in \mathbb{N}} \subset \mathbb{R}$ una sucesión de números reales, entonces:

i. $\limsup\limits_{n} a_n = \lim\limits_{n \rightarrow +\infty} \sup\limits_{k \geq n} a_n$
ii. $\liminf\limits_{n} a_n = \lim\limits_{n \rightarrow +\infty} \inf\limits_{k \geq n} a_n$

#### Definición 1.10: Limite superior e inferior de conjuntos

Sea $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}$ una sucesión de conjuntos, entonces:

i. $\limsup\limits_{n} A_n = \bigcap\limits_{n = 1}^{+\infty} \bigcup\limits_{k = n}^{+\infty} A_k$
i. $\liminf\limits_{n} A_n = \bigcup\limits_{n = 1}^{+\infty} \bigcap\limits_{k = n}^{+\infty} A_k$

#### Proposición 1.11: propiedades del límite superior e inferior

***

1) $\limsup\limits_{n} A_n = \{ \omega \in \Omega / \omega \in A_n \text{ para infinitos valores de } n \}$

*Dem*: dado que se trata de una igualdad de conjuntos, debemos demostrar la doble inclusión.

\vspace{0.2cm}

Parte 1: $\{ \omega \in \Omega / \omega \in A_n \text{ para infinitos valores de } n \} \subset \limsup\limits_{n} A_n$

Si $\omega$ pertenece a infinitos $A_n \Rightarrow \forall n$, $\exists n_0 \geq n / \omega \in A_{n_0}$. Luego si $\omega \in A_{n_0} \Rightarrow \omega \in \bigcup\limits_{k = n_0}^{+\infty} A_k \, \forall n$ dado que $n_0 \geq n$. Por lo tanto, $\omega \in \bigcap\limits_{n = 1}^{+\infty} \bigcup\limits_{k = n}^{+\infty} A_k = \limsup\limits_{n} A_n$

Parte 2: $\limsup\limits_{n} A_n \subset \{ \omega \in \Omega / \omega \in A_n \text{ para infinitos valores de } n \}$

Demostración por absurdo. Si $\omega$ pertenece a una cantidad finita de $A_n \Rightarrow \exists n / \forall n_1 \geq n$, $\omega \notin A_{n_1} \Rightarrow \omega \notin \bigcup\limits_{k = n_1}^{+\infty} A_k \Rightarrow \omega \notin \bigcap\limits_{n=1}^{+\infty} \bigcup\limits_{k = n_1}^{+\infty} A_k$

***

2) $\liminf\limits_{n} A_n = \{ \omega \in \Omega / \omega \in A_n \forall n \text{ salvo, a lo sumo, una cantidad finita de índices} \}$

*Dem*: dado que se trata de una igualdad de conjuntos, debemos demostrar la doble inclusión.

\vspace{0.2cm}

Parte 1: $\liminf\limits_{n} A_n \subset \{ \omega \in \Omega / \omega \in A_n \forall n \text{ salvo, a lo sumo, una cantidad finita de índices} \}$

$\exists n / \forall n_0 \geq n$, $\omega \in A_n \Rightarrow \omega \in \bigcap\limits_{k = n}^{+\infty} A_k \Rightarrow \omega \in \bigcup\limits_{n = 1}^{+\infty} \bigcap\limits_{n = k}^{+\infty} A_k$

Parte 2: $\{ \omega \in \Omega / \omega \in A_n \forall n \text{ salvo, a lo sumo, una cantidad finita de índices} \} \subset \liminf\limits_{n} A_n$

Si $\omega \in \bigcup\limits_{n = 1}^{+\infty} \bigcap\limits_{k = n}^{+\infty} A_k \Rightarrow \exists n_0 / \omega \in A_k \, \forall k \geq n_0$

***

3) $\liminf\limits_{n} A_n \subset \limsup\limits_{n} A_n$

*Dem*: a continuación se demuestra que si $\omega$ pertenece al límite inferior, entonces debe existir un índice, $n_0$, a partir del cual $\omega$ pertenece a todos los $A_k$, dado que esa es la condición para pertenecer a la intersección de los conjuntos. Pero, en el enunciado 1 de la proposición se demostró que si $\omega$ pertenece a una cantidad infinita de índices, entonces pertenece al límite superior. 

Si $\omega \in \liminf\limits_{n} A_n \Rightarrow \exists n_0$ a partir del cual $\omega \in \bigcup\limits_{n=1}^{+\infty} \bigcap\limits_{k =n}^{+\infty} A_k \, \forall n \geq n_0 \Rightarrow \omega$ pertenece a una cantidad infinita de índices (todos ellos a partir de $n_0$) $\Rightarrow \omega \in \limsup\limits_{n} A_n$

***

4) Como la sucesión $B_n = \bigcup\limits_{k = n}^{+\infty} A_k$ es decreciente, entonces:
$$P \left( \limsup\limits_{n} A_n \right) = \lim\limits_{n \rightarrow + \infty} P \left( \bigcup\limits_{k = n}^{+\infty} A_n \right)$$

*Dem*: veamos primero que la sucesión $B_n$ es decreciente. La misma está defiinida de la siguiente forma:

$$\begin{array}{l c c c c c c c c}
B_n & = & A_n & \cup & A_{n+1} & \cup & A_{n+2} & \cup & \ldots \\
B_{n+1} & = &  &  & A_{n+1} & \cup & A_{n+2} & \cup & \ldots \\
B_{n+2} & = &  &  &  &  & A_{n+2} & \cup & \ldots \\
\,\,\,\,\,\, \vdots & & & & & & & & 
\end{array}$$

Dado que cada vez unimos menos conjuntos, el conjunto resultante es "más chico", y por tanto, la sucesión es decreciente. Luego entonces,
$$\begin{array}{c c l c l}
P \left( \limsup\limits_{n} A_n \right) & = & P \left( \bigcap\limits_{n = 1}^{+\infty} \bigcup\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de límite superior} \\ \\
& = & P \left( \bigcap\limits_{n = 1}^{+\infty} B_n \right) & & \text{por definición de $B_n$} \\ \\
& = & \lim\limits_{n \rightarrow +\infty} P(B_n) & & \text{por continuidad de la probabilidad de una} \\
& & & & \text{sucesión decreciente (ver prop 1.8/8)} \\ \\
& = & \lim\limits_{n \rightarrow +\infty} P \left( \bigcup\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de $B_n$}
\end{array}$$

***

5) Como la sucesión $B_n = \bigcap\limits_{k = n}^{+\infty} A_k$ es creciente, entonces:
$$P \left( \liminf\limits_{n} A_n \right) = \lim\limits_{n \rightarrow + \infty} P \left( \bigcap\limits_{k = n}^{+\infty} A_n \right)$$

*Dem*: veamos primero que la sucesión $B_n$ es creciente. La misma está defiinida de la siguiente forma:

$$\begin{array}{l c c c c c c c c}
B_n & = & A_n & \cap & A_{n+1} & \cap & A_{n+2} & \cap & \ldots \\
B_{n+1} & = &  &  & A_{n+1} & \cap & A_{n+2} & \cap & \ldots \\
B_{n+2} & = &  &  &  &  & A_{n+2} & \cap & \ldots \\
\,\,\,\,\,\, \vdots & & & & & & & & 
\end{array}$$
Dado que cada vez intersectamos menos conjuntos, el conjunto resultante es "más grande", y por tanto, la sucesión es creciente. Luego entonces,

$$\begin{array}{c c l c l}
P \left( \liminf\limits_{n} A_n \right) & = & P \left( \bigcup\limits_{n = 1}^{+\infty} \bigcap\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de límite inferior} \\ \\
  & = & P \left( \bigcup\limits_{n = 1}^{+\infty} B_n \right) & & \text{por definición de $B_n$} \\ \\
  & = & \lim\limits_{n \rightarrow +\infty} P(B_n) & & \text{por continuidad de la probabilidad de una } \\
  &   &  & & \text{sucesión creciente (ver prop 1.8/7)} \\ \\
  & = & \lim\limits_{n \rightarrow +\infty} P \left( \bigcap\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de $B_n$}
\end{array}$$

***

6) Si $\{A_n\}_{n \in \mathbb{N}}$ es creciente, entonces: $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n = \bigcup\limits_{n = 1}^{+\infty} A_n$

*Dem*: dado que se trata de una triple igualdad entre conjuntos, debemos demostrar dos de los pares de doble inclusiones, y el tercero se cumplirá por transitividad.

Parte 1: $\liminf\limits_{n} A_n = \bigcup\limits_{n = 1}^{+\infty} A_n$

- Parte 1.i: $\liminf\limits_{n} A_n \subset \bigcup\limits_{n = 1}^{+\infty} A_n$

Si $\omega \in \liminf\limits_{n} A_n \Rightarrow \omega \in \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k$. Pero si la sucesión es creciente, entonces $\bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k = \bigcup\limits_{n \in \mathbb{N}} A_n \Rightarrow \omega \in \bigcup\limits_{n \in \mathbb{N}} A_n \Rightarrow \liminf\limits_{n} A_n \subset \bigcup\limits_{n = 1}^{+\infty} A_n$.

- Parte 1.ii: $\bigcup\limits_{n = 1}^{+\infty} A_n \subset \liminf\limits_{n} A_n$

Si la sucesión es creciente, entonces $\bigcup\limits_{n \in \mathbb{N}} A_n = \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k$. Por lo tanto, $\forall \omega \in \bigcup\limits_{n \in \mathbb{N}} A_n$, $\omega \in \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k = \liminf_n A_n$. Por lo tanto, $\bigcup\limits_{n = 1}^{+\infty} A_n \subset \liminf\limits_{n} A_n$

\vspace{0.2cm}

Parte 2: $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$

- Parte 2.i: $\liminf\limits_{n} A_n \subset \limsup\limits_{n} A_n$

Ver demostración de prop 1.11/3 (no se requiere que la sucesión sea creciente).

- Parte 2.ii: $\limsup\limits_{n} A_n \subset \liminf\limits_{n} A_n$

Si $\omega \in \limsup\limits_n A_n$ entonces $\omega$ pertenece a infinitos $A_n$ (ver demostración de prop 1.11/1). Pero dado que la sucesión es creciente, $\exists n_0$ tal que $\omega \in A_n \, \forall n \geq n_0$. Pero esto implica que $\omega \notin A_n$ solo para aquellos valores de $n < n_0$. Entonces $\omega$ no pertenece a una cantidad finita de índices. Por lo tanto, $\omega \in \liminf\limits_n A_n$ 

\vspace{0.2cm}

De lo anterior se desprende que $\liminf\limits_{n} A_n = \bigcup\limits_{n = 1}^{+\infty} A_n$ (parte 1) y que $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$ (parte 2). Por transitividad entonces $\bigcup\limits_{n = 1}^{+\infty} A_n = \limsup\limits_{n} A_n$, por lo que queda demostrado el teorema.

***

7) Si $\{A_n\}_{n \in \mathbb{N}}$ es decreciente, entonces: $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n = \bigcap\limits_{n = 1}^{+\infty} A_n$

*Dem*: dado que se trata de una triple igualdad entre conjuntos, debemos demostrar dos de los pares de doble inclusiones, y el tercero se cumplirá por transitividad.

Parte 1: $\limsup\limits_n A_n = \bigcap\limits_{n \in \mathbb{N}} A_n$

- Parte 1.i: $\limsup\limits_n A_n \subset \bigcap\limits_{n \in \mathbb{N}} A_n$

Si $\omega \in \limsup\limits_{n} A_n \Rightarrow \omega \in \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k$. Pero si la sucesión es decreciente, entonces $\bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k = \bigcap\limits_{n \in \mathbb{N}} A_n \Rightarrow \omega \in \bigcap\limits_{n \in \mathbb{N}} A_n \Rightarrow \limsup\limits_{n} A_n \subset \bigcap\limits_{n = 1}^{+\infty} A_n$.

- Parte 1.ii: $\bigcap\limits_{n \in \mathbb{N}} A_n \subset \limsup\limits_n A_n$

Si la sucesión es decreciente, entonces $\bigcap\limits_{n \in \mathbb{N}} A_n = \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k$. Por lo tanto, $\forall \omega \in \bigcap\limits_{n \in \mathbb{N}} A_n$, $\omega \in \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k = \limsup_n A_n$. Por lo tanto, $\bigcap\limits_{n = 1}^{+\infty} A_n \subset \limsup\limits_{n} A_n$

\vspace{0.2cm}

Parte 2: $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$

- Parte 2.i: $\liminf\limits_{n} A_n \subset \limsup\limits_{n} A_n$

Ver demostración de prop 1.11/3 (no se requiere que la sucesión sea decreciente).

- Parte 2.ii: $\limsup\limits_{n} A_n \subset \liminf\limits_{n} A_n$

Si $\omega \in \liminf\limits_n A_n$ entonces $\omega$ pertenece a todos los $A_n$ salvo, a lo sumo, a una cantidad finita de ellos (ver demostración de prop 1.11/2). Luego, si $\omega \in \limsup\limits_n A_n \Rightarrow \omega \in \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k$, pero si $\{A_n\}_{n \in \mathbb{N}}$ es decreciente, entonces $\omega \in \bigcap\limits_{n \in \mathbb{N}} A_n \Rightarrow$ por definición de intersección, $\omega \in A_n \, \forall n \Rightarrow \omega \in \liminf\limits_n A_n$

\vspace{0.2cm}

De lo anterior se desprende que $\limsup\limits_{n} A_n = \bigcap\limits_{n = 1}^{+\infty} A_n$ (parte 1) y que $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$ (parte 2). Por transitividad entonces $\bigcap\limits_{n = 1}^{+\infty} A_n = \liminf\limits_{n} A_n$, por lo que queda demostrado el teorema.

***

8) $P \left( \liminf\limits_{n} A_n \right) \leq \liminf\limits_{n} P(A_n) \leq \limsup\limits_{n} P(A_n) \leq P \left( \limsup\limits_{n} A_n \right)$

*Dem*: debemos demostrar tres de las cuatro desigualdades. La última queda demostrada por transitividad.

Parte 1: $P \left( \liminf\limits_{n} A_n \right) \leq \liminf\limits_{n} P(A_n)$

$$\begin{array}{c c l c l}
P \left( \liminf\limits_{n} A_n \right) & = & P \left( \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k \right) & & \text{por definición de límite inferior} \\ \\
  & = & P \left( \bigcup\limits_{n \in \mathbb{N}} B_n \right) & & \text{definiendo a $B_n = \bigcap\limits_{k \geq n} A_k$} \\ \\
  & = & \lim\limits_n P(B_n) & & \text{por ser $B_n$ creciente} \\ \\
  & = & \lim\limits_n P \left( \bigcap\limits_{k \geq n} A_k \right) & & \text{por definición de $B_n$} \\ \\
  & = & \liminf\limits_n P \left( \bigcap\limits_{k \geq n} A_k \right) & & \text{por ser el primero el límite de una sucesión} \\ \\
  & \leq & \liminf\limits_n P(A_k) \,\,\, \forall k \geq n & & \text{por definición de intersecsión}
\end{array}$$

\newpage

Parte 2: $\liminf\limits_{n} P(A_n) \leq \limsup\limits_{n} P(A_n)$

En este caso estamos hablando del límite inferior y del límite superior de una sucesión real, los cuales se definen como:

- $\liminf\limits_n P(A_n) = \lim\limits_n \left[ \inf\limits_{k \geq n} P(A_n) \right]$
- $\limsup\limits_n P(A_n) = \lim\limits_n \left[ \sup\limits_{k \geq n} P(A_n) \right]$

Por lo tanto, $\liminf\limits_n P(A_n) \leq \limsup\limits_n P(A_n)$

Parte 3: $\limsup\limits_{n} P(A_n) \leq P \left( \limsup\limits_{n} A_n \right)$

$$\begin{array}{c c l c l}
P \left( \limsup\limits_{n} A_n \right) & = & P \left( \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k \right) & & \text{por definición de límite superior} \\ \\
  & = & P \left( \bigcap\limits_{n \in \mathbb{N}} B_n \right) & & \text{definiendo a $B_n = \bigcup\limits_{k \geq n} A_k$} \\ \\
  & = & \lim\limits_n P(B_n) & & \text{por ser $B_n$ decreciente} \\ \\
  & = & \lim\limits_n P \left( \bigcup\limits_{k \geq n} A_k \right) & & \text{por definición de $B_n$} \\ \\
  & = & \limsup\limits_n P \left( \bigcup\limits_{k \geq n} A_k \right) & & \text{por ser el primero el límite de una sucesión} \\ \\
  & \geq & \limsup\limits_n P(A_k) \, \forall k \geq n & & \text{por definición de unión}
\end{array}$$

# Independencia

#### Definición 1.12

Dada una familia de sucesos $\{A_{\alpha}\}_{\alpha \in I}$, donde $I$ es un conjunto cualquiera de índices, se dice que son independiente si, y solo si, para todo $F \subset I$ finito, se cumple que:
$$ P \left( \bigcap\limits_{\alpha \in F} A_{\alpha}  \right) = \prod\limits_{\alpha \in F} P(A_{\alpha}) $$

\newpage

#### Teorema 1.13: Lema de Borel-Cantelli

Dada una sucesión $\{A_n\}_{n \in \mathbb{N}} \subset \mathcal{A}$,

***

i. Si $\sum\limits_{n = 1}^{+\infty} P(A_n) < \infty \Rightarrow P \left( \limsup\limits_n A_n \right) = 0$

*Dem*: 

$$\begin{array}{c c l c l}
P \left( \limsup\limits_n A_n \right) & = & \lim\limits_{n \rightarrow +\infty} P \left(  \bigcup\limits_{k = n}^{+\infty} A_k \right) & & \text{por prop. 1.11/4} \\ \\
  & \leq & \sum\limits_{k = n}^{+\infty} P(A_k) & & \text{prop. 1.9/6} \\ \\
  &      & \sum\limits_{k = n}^{+\infty} P(A_k) \overset{n}{\rightarrow} 0 & & \text{por ser la cola de una serie convergente}
\end{array}$$

***

ii. Si $\sum\limits_{n = 1}^{+\infty} P(A_n) = \infty$ y además $\{A_n\}_{n \in \mathbb{N}}$ son independientes $\Rightarrow P \left( \limsup\limits_n A_n \right) = 1$

*Dem*: como $P \left( \limsup\limits_n A_n \right) = \lim\limits_{n \rightarrow +\infty} P \left(  \bigcup\limits_{k = n}^{+\infty} A_k \right)$ basta probar que $\lim\limits_{n \rightarrow +\infty} P \left(  \bigcap\limits_{k = n}^{+\infty} A^c_k \right) \overset{n}{\rightarrow} 0$. Para cada $m > n$ tenemos que:

$$\begin{array}{c c l c l}
P \left(  \bigcap\limits_{k = n}^{+\infty} A^c_k \right) & \leq & P \left(  \bigcap\limits_{k = n}^{m} A^c_k \right) & & \text{por intersección} \\ \\
  & = & \prod\limits_{k = n}^{m} P \left( A_k^c \right) & & \text{por independencia} \\ \\
  & = & \prod\limits_{k = n}^{m} \left[ 1 - P \left( A_k \right) \right] & & \text{por probabilidad del complemento} \\ \\
  & \leq & \prod\limits_{k = n}^{m} \exp\left\{ -P(A_k) \right\} & &  \text{por que } 1 - x \leq e^{-x} \, \forall x \\ \\
  & = & \exp\left\{ \sum\limits_{k = n}^{m} -P(A_k) \right\} & & \text{por propiedad de la potencia} \\ \\
  &   & \exp\left\{ - \sum\limits_{k = n}^{m} P(A_k) \right\} \overset{m}{\rightarrow} 0 & & \text{porque } \lim\limits_m \sum\limits_{k = n}^{m} P(A_k) = - \infty
\end{array}$$

\newpage

# Variables aleatorias

## Espacio métrico

#### Definición 1.14

Una métrica definida en un conjunto $F$ es una función $d: F \times F \rightarrow \mathbb{R}$ tal que:

i. $d(x,y) \geq 0$ y $d(x,y) = 0 \Leftrightarrow x = y$

ii. $d(x,y) = d(y,x)$

iii. para todo $z \in F$, se cumple que $d(x,y) \leq d(x,z) + d(z,y)$

#### Definición 1.16: conjunto abierto y conjunto cerrado

Dado un espacio métrico $(F,d)$ se dice que un conjunto $A \subset F$ es avierto, si para todo $a \in A$, existe $r > 0$ tal que $B(a,r) \subset A$, siendo $B(a,r) = \{ x \in F / d(a,x) < r \}$. Se dice que $A$ es cerrado si $A^c$ es abierto.

#### Proposición 1.17: propiedades de un espacio métrico

Dado un espacio métrico $(F,d)$ se verifica que:

***

1. $\emptyset$ y $F$ son conjuntos abiertos.

*Dem*: requiere demostrar ambas afirmaciones.

Parte 1: $\emptyset$ es abierto. 

Esta es una verdad vacua, dado que no exisiten elementos que pertenezcan al conjunto. Por lo tanto, es vacuamente cierto, que para todos sus elementos, existe un radio que define una bola abierta, centrada en dicho elemento, completamente contenida en el vacio. 

Parte 2: $F$ es abierto.

Debemos demostrar que $\forall x \in F$, existe un radio $r$ tal que $B(x,r) \subset F$. Pero la definición de bola abierta es para los $x$ que pertenecen a $F$ (ver definición 1.16). Por lo tanto, todos los puntos que pertenezcan a la bola (para cualquier $x$ considerado) pertenecerán a $F$ por definición. Por lo tanto, siempre existe dicho radio $r$, por lo que $F$ es abierto.

***

\newpage

2. Si $\{F_{\alpha}\}_{\alpha \in I} \subset F$ es una familia cualquiera de conjuntos abiertos, entonces $\bigcup\limits_{\alpha \in I} F_{\alpha}$ es abierto.

*Dem*: $\forall a \in \bigcup\limits_{\alpha \in I} F_{\alpha}$, $\exists \alpha$ tal que $a \in F_{\alpha}$ por definición de unión. Luego, dado que $F_{\alpha}$ es abierto por hipótesis, $\forall a \in \bigcup\limits_{\alpha \in I} F_{\alpha}$, $\exists r_a$, tal que $B(a.r) \subset F_{\alpha} \subset \bigcup\limits_{\alpha \in I} F_{\alpha}$. Por lo tanto, la unión de conjuntos abiertos, es abierta.

***

3. Para todo $k > 0$, si $F_1, \, \ldots, \, F_k$ son abiertos, entonces $F_1 \cap \ldots \cap F_k$ es abierta.

*Dem*: sean $F_i$ y $F_j$ dos miembros de $F_1, \, \ldots, \, F_k$.

- Si $F_i \cap F_j = \emptyset \Rightarrow F_i \cap F_j$ es abierto, dado que por la parte 1 de la proposción, $\emptyset$ es abierto.

- Si $F_i \cap F_j \neq \emptyset \Rightarrow$ por definición de intersección, $\forall x \in (F_i \cap F_j)$, $x \in F_i$ y $x \in F_j$. Dado que tanto $F_i$ como $F_j$ son abiertos por hipótesis, lo anterior implica que $\exists r_x^i$ tal que $B(x,r^i_x) \subset F_i$, y $\exists r_x^j$, tal que $B(x,r^j_x) \subset F_j$. Pero esto implica que $\exists r_x = \min\{r_x^i, r_x^j \}$ tal que $B(x,r_x) \subset (F_i \cap F_j) \, \forall x$. Por lo tanto, $F_i \cap F_j$ es abierto.

Llamemos ahora $F_{ij} = F_i \cap F_j$ y repitamos el proceso para $F_{ij} \cap F_h$, siendo $F_h$ otro miembro de $F_1, \, \ldots, \, F_k$.

- Si $F_{ij} \cap F_h = \emptyset \Rightarrow F_{ij} \cap F_h$ es abierto, dado que por la parte 1 de la proposción, $\emptyset$ es abierto.

- Si $F_{ij} \cap F_h \neq \emptyset \Rightarrow$ por definición de intersección, $\forall x \in (F_{ij} \cap F_h)$, $x \in F_{ij}$ y $x \in F_h$. Dado que tanto $F_{ij}$ como $F_h$ son abiertos por (el primero por lo demostrado anteriormente, el segundo por hipótesis), lo anterior implica que $\exists r_x^{ij}$ (por ejemplo, el hallado en la parte anterior), tal que $B(x,r^{ij}_x) \subset F_{ij}$, y $\exists r_x^h$, tal que $B(x,r^h_x) \subset F_h$. Pero esto implica que $\exists r_x = \min\{r_x^{ij}, r_x^h \}$ tal que $B(x,r_x) \subset (F_{ij} \cap F_h) \, \forall x$. Por lo tanto, $F_{ij} \cap F_h$ es abierto.

Repitiendo lo anterior hasta intersectar todos los $k$ conjuntos, obtenemos que la intersección de todos ellos es abierta.

***

#### Convergencia de sucesiones en un espacio métrico

- Si $\{x_n\}_{n \in \mathbb{N}} \subset F$ es una sucesión, $x_n \rightarrow x \Leftrightarrow d(x_n, x) \rightarrow 0$.

- Decimos que una sucesión $\{x_n\}_{n \in \mathbb{N}} \subset F$ es de Cauchy $\Leftrightarrow d(x_n,x_m) \rightarrow 0$ cuando $n,m \rightarrow \infty$.

\newpage

#### Espacio métrico completo

- Se dice que el espacio métrico es completo si para toda $\{x_n\}_{n \in \mathbb{N}} \subset F$ de Cauchy, existe $x \in F$ tal que $x_n \rightarrow x$.

#### Continuidad de funciones

- Sea $(G, \rho)$ otro espacio métrico, se dice que $f : F \rightarrow G$ es continua en $x \in F$ si para toda $x_n \rightarrow x$, $\rho\big( f(x_n), f(x) \big) \rightarrow 0$.

- También, $f : F \rightarrow G$ es continua $\Leftrightarrow \forall B \in G$ abierto, $f^{-1}(B) = \{a \in F / f(a) \in B \}$ es abierto en $F$.

#### Definición 1.18: $\sigma$-álgebra de Borel en $\mathbb{R}$

Dado un espacio métrico $(F,d)$ la $\sigma$-álgebra de Borel de $F$ es la intersección de todas las $\sigma$-álgebras que contienen a los conjuntos abiertos. Se denota: $\mathcal{B}(F)$.

#### Definición 1.19: variable aleatoria

Dado un espacio de probabilidad $(\Omega, \mathcal{A}, P)$ y un espacio métrico $(F,d)$, direms que $X : \Omega \rightarrow F$ es una variable aleatoria si para todo $B \in \mathcal{B}(F)$, se cumple que:
$$X^{-1}(B) = \{ \omega \in \Omega / X(\omega) \in B \} \in \mathcal{A}$$

#### Proposición 1.20

Para verificar que $X$ es una variable aleatoria, basta probar que $X^{-1}(B) \in \mathcal{A}$ para todo $B \in F$ abierto.

*Dem*:

#### Teorema 1.21: la transformación medible de una v.a., es otra v.a.

Sean $(F,d)$ y $(G, \rho)$ espacios métricos. Si $X : \Omega \rightarrow F$ es una variable aleatoria y $g : F \rightarrow G$ es una función continua, entonces $Y = g(X)$ es una variable aleatoria a valores de $G$.

#### Corolario 1.22

Sean $X,Y : \Omega \rightarrow \mathbb{R}$ son variables aleatorias, y $\alpha \in \mathbb{R}$ entonces:

i. $X + \alpha Y$ es una variable aleatoria
ii. $XY$ es una variable aleatoria

#### Observación 1.23: variables aleatorias a los reales extendidos

En algunos casos es necesario considrar variables aleatorias a los reales extendidos: $\bar{\mathbb{R}} = \mathbb{R} \cup \{-\infty, +\infty\}$. Definimos una $\sigma$-álgebra generadad por $\bar{\mathbb{R}}$ como:
$$\mathcal{B}(\bar{\mathbb{R}}) = \mathcal{B}(\mathbb{R}) \cup \big\{A \cup \{-\infty, +\infty\} / A \in \mathcal{B}(\mathbb{R}) \big\} \cup \big\{A \cup \{+\infty\} / A \in \mathcal{B}(\mathbb{R}) \big\} \cup \big\{A \cup \{-\infty\} / A \in \mathcal{B}(\mathbb{R}) \big\}$$

#### Teorema 1.24 y Corolario 1.25

Si $X_n : \Omega \rightarrow \mathbb{R}$ es una variable aleatoria para todo $n \in \mathbb{N}$, entonces también lo son las variables aleatorias a valores en $\bar{\mathbb{R}}$:

i. $\sup\limits_n X_n$

ii. $\inf\limits_n X_n$

iii. $\limsup\limits_n X_n$

iv. $\liminf\limits_n X_n$

#### Definición 1.26

Dadas dos variables aleatorias $X,Y : \Omega \rightarrow F$ decimos que:

1. $X$ es igual a $Y$ en distribución, si $\forall A \in \mathcal{B}(F)$, $P(X \in A) = P(Y \in A)$, y lo notamos como $X \overset{d}{=} Y$.

2. $X$ es igual a $Y$ casi seguramente, si $\exists C \subset \Omega$ con $P(C) = 1 / \forall \omega \in C$, $X(\omega) = Y(\omega)$, y lo notamos como $X \overset{cs}{=} Y$.

#### Observación 1.27

Si $X \overset{cs}{=} Y \Rightarrow X \overset{d}{=} Y$. El recíproco no es cierto.

\newpage

## Ley 0 o 1 de Kolmogorov\footnote{Lo siguiente fue presentado en clase y no sigue las notas de Cholaquidis (dado que las mismas son inentendibles).}

#### Definiciones

Dados $(\Omega, \mathcal{A}, P)$ y $X_1, \, \ldots, \, X_n, \, \ldots$ una sucesión de variables aleatorias independientes sean:

1. $\mathcal{F}_{\infty} = \sigma(X_1, \, \ldots, \, X_n, \, \ldots) \subset \mathcal{A}$
2. $\mathcal{F}_n = \sigma(X_1, \, \ldots, \, X_n) \subset \mathcal{A}$
3. $\mathcal{F}_n' = \sigma(X_n, \, X_{n+1}, \, \ldots) \subset \mathcal{A}$

Se define la $\sigma$-álgebra cola como:
$$\tau = \bigcap\limits_{n \in \mathbb{N}} \mathcal{F}_n'$$

#### Ley 0 o 1 de Kolmogorov

Sea $A \subset \tau \Rightarrow P(A) = 0$ o $P(A) = 1$

*Dem*:

a. $A \subset \tau = \bigcap\limits_{n \in \mathbb{N}} \mathcal{F}_n' \subset \mathcal{F}_{\infty}$

b. $\left. \begin{array}{l} A \in \mathcal{F}_n' \\ \mathcal{F}_n \perp \mathcal{F}_n' \end{array} \right\} \Rightarrow A \perp \mathcal{F}_n \Rightarrow A \perp \bigcup\limits_{n \in \mathbb{N}} \mathcal{F}_n \Rightarrow A \perp \sigma \left( \bigcup\limits_{n \in \mathbb{N}} \mathcal{F}_n \right) \Rightarrow A \perp \mathcal{F}_{\infty}$

Por a. y b. obtenemos que $A \perp A$. Por lo tanto, $P(A) = P(A \cap A) = P(A) \, P(A) = P^2(A)$. Pero como $P(A)$ es una probabilidad, $0 \leq P(A) \leq 1$, entonces, $P(A) = 0$ o $P(A) = 1$ dado que estos son los únicos números que elevados al cuadrado dan como resultado ellos mismos.

## Desigualdad de Kolmogorov

Sean $X_1, \, X_2, \, \ldots, \, X_n$ variables aleatorias independientes tales que $E(X_i) = 0$ y $E(X_i^2) < \infty$ $\forall i = 1, \, \ldots, \, n$, y sea $S_k = X_1 + \ldots + X_k$, entonces, $\forall \varepsilon > 0$:

1. $P \left( \max\limits_{1 \leq k \leq n} |S_k| \geq \varepsilon \right) \leq \frac{ E(S_n^2) }{ \varepsilon^2 }$

2. Si además existe $c > 0$ tal que $P(|X_i| \leq c) = 1 \,\,\, \forall i$ entonces,
$$ P \left( \max\limits_{1 \leq k \leq n} |S_k| \geq \varepsilon \right) \geq 1 - \frac{ (c + \varepsilon)^2 }{ E(S_n^2) } $$

\newpage

*Dem*: Parte 1)

Sean:

i. $A = \left\{ \max\limits_{1 \leq k \leq n} |S_k| \geq \varepsilon \right\}$
ii. $A_k = \big\{ |S_i| < \varepsilon, \, i = 1, \, \ldots, \, k-1, |S_k| \geq \varepsilon \big\}$ para $k = 1, \, \ldots \, n$ con $S_0 = 0$

Observese que $A_i \cap A_j = \emptyset \,\,\, \forall i \neq j$ y $A = \bigcup\limits_{k = 1}^{n} A_k$. Por lo tanto,
$$ E(S_n^2) \geq E(S_n^2 \mathbb{I}_A) = \sum\limits_{k = 1}^{n} E(S_n^2 \mathbb{I}_{A_k}) $$

Para cada una de las esperanzas del último sumando tenemos que:
$$ E(S_n^2 \mathbb{I}_{A_k}) = E \Big[ \big( S_k + (X_{k+1} + \ldots + X_n) \big)^2 \mathbb{I}_{A_k} \Big] = $$
$$ = E(S_k^2 \mathbb{I}_{A_k}) + 2 \underbrace{ E \Big[ S_k (X_{k+1} + \ldots + X_n) \mathbb{I}_{A_k} \Big] }_{ \substack{ = 0 \text{, dado que las variables } \\ X_{k+1} + \ldots + X_n \text{ son centradas} \\ \text{ e independientes de } S_k \mathbb{I}_{A_k} }} + E \big[(X_{k+1} + \ldots + X_n)^2 \mathbb{I}_{A_k} \big] = $$
$$ = E(S_k^2 \mathbb{I}_{A_k}) + E \big[(X_{k+1} + \ldots + X_n)^2 \mathbb{I}_{A_k} \big] \geq E(S_k^2 \mathbb{I}_{A_k}) $$

Si $\omega \in A_k \Rightarrow$ por definición de $A_k$, $|S_k(\omega)| \geq \varepsilon$, es decir, $E(S_k^2 \mathbb{I}_{A_k}) \geq \varepsilon^2 P(A_k)$. Por lo tanto,
$$E(S_n^2) \geq \sum\limits_{k = 1}^{n} E(S_k^2 \mathbb{I}_{A_K}) \geq \varepsilon^2 \sum\limits_{k = 1}^{n} P(A_k) = \varepsilon^2 P(A) = \varepsilon^2 P \left( \max\limits_{1 \leq k \leq n} |S_k| \geq \varepsilon \right) \Rightarrow$$
$$\Rightarrow P \left( \max\limits_{1 \leq k \leq n} |S_k| \geq \varepsilon \right) \leq \frac{ E(S_n^2) }{ \varepsilon2 }$$

#### Corolario 1.30 Desigualdad de Markov

$$P ( |X - E(X)| > \varepsilon) \leq \frac{V(X)}{\varepsilon^2}$$

\newpage

# Integral de Riemann-Stieltjes

## Definición

#### Definición 1.31: Integral de Riemann-Stieltjes

Dadas $g,F : [a,b] \rightarrow \mathbb{R}$ y $P = \{ a = c_0 < c_1 < c_2 < \ldots < c_n = b\}$,

- definimos la suma parcial de Riemann-Stieltjes como: 
$$S(P,g,F) = \sum\limits_{i = 1}^{n} g(x_i) \big[ F(c_i) - F(c_{i-1}) \big] \,\,\,\, \text{con } x_i \in [c_{i-1}, c_i]$$

- definimos la norma de la partición $P$ como: $||P|| = \max\{c_i - c_{i-1}, \,\,\, i = 1, \ldots, n \}$

- decimos que $\lim\limits_{||P|| \rightarrow 0} S(P,g,F) = I \Leftrightarrow \forall \varepsilon > 0$, $\exists \delta > 0$ tal que para toda partición $P$ del intervalo $[a,b]$ con $||P|| < \delta$ se tiene que $|S(P,g,F) - I| < \varepsilon$. En este caso decimos que la integral de Riemann-Stieltjes de $g$ respecto de $F$ en el intervalo $[a,b]$ existe y vale $I$, y lo denotamos como:
$$ \int\limits_a^b g(x) d F(x) $$

#### Observación 1.32

i. Si $F(x) = x$ obtenemos la integral de Riemann:

*Dem*: $\int\limits_a^b g(x) dF(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(x_i) \big[ F(c_i) - F(c_{i-1}) \big] = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(x_i) \big[ c_i - c_{i-1} \big] = \int\limits_a^b g(x) dx$

2. Si $F(x) = k$, $\int\limits_a^b g(x)dF(x) = 0$ para toda $g$.

*Dem*: $\int\limits_a^b g(x) dF(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(x_i) \big[ F(c_i) - F(c_{i-1}) \big] = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(x_i) \big[ k - k \big] = 0 \,\,\, \forall g$

3. Si $g : [a,b] \rightarrow \mathbb{R}$ es continua y $F(x) = \mathbb{I}_{[c,b]}(x)$ con $c \in (a,b)$ entonces:
$$\int\limits_a^b g(x) d F(x) = g(c)$$

*Dem*: debemos discutir en función de si $c$ pertenece o no a la partición (es decir, si el valor $c$ considerado es uno de los $c_i$ en la partición).

\newpage

Caso a) $c \notin P$

Consideremos el intervalo de la partición tal que $c_j < c < c_{j+1}$. Que $c$ no pertenezca a la partición implica que $F(c_j) = 0$ mientras que $F(c_{j+1}) = 1$ dado que $F$ es la indicatriz del intervalo $[c,b]$. Para todos los demás subintervalos de la partición, $F(x) = k$ por lo que la integral R-S vale cero (ver observación anterior). Por lo tanto,
$$ \int\limits_a^b g(x) d F(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(x_i) \big[ F(c_i) - F(c_{i-1}) \big] = \lim\limits_{||P|| \rightarrow 0} g(x_j = c) \big[ F(c_{j+1}) - F(c_j) \big] = $$
$$ = \lim\limits_{||P|| \rightarrow 0} g(c) \big[ 1 - 0 \big] = \lim\limits_{||P|| \rightarrow 0} g(c) = g(c)$$

Caso b) $c \in P$

Consideremos el intervalo de la patición tal que $c_{j-1} < c_j = c$. Dado que $F(x) = \mathbb{I}_{[c,b]}$, $F(c_{j-1}) = 0$ y $F(c_j) = F(c) = 1$. De nuevo, para todos los demás sub-intervalos de la partición, $F(x) = k$ por lo que la suma parcial sobre dichos sub-intervalos vale cero. Por lo tanto,
$$ \int\limits_a^b g(x) d F(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(x_i) \big[ F(c_i) - F(c_{i-1}) \big] = \lim\limits_{||P|| \rightarrow 0} g(x_j = c) \big[ F(c_j = c) - F(c_{j - 1}) \big] =$$
$$ = \lim\limits_{||P|| \rightarrow 0} g(c) \big[ 1 - 0 \big] = \lim\limits_{||P|| \rightarrow 0} g(c) = g(c)$$

4. Si $g(x) = k \Rightarrow \forall F$, $\int\limits_a^b g(x) d F(x) = k [F(b) - F(a)]$  

*Dem*: se desprende de que la sumatoria se vuelve telescópica cuando $g(x) = k$.

$$ \int\limits_a^b g(x) d F(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(x_i) \big[ F(c_i) - F(c_{i-1}) \big] = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} k \big[ F(c_i) - F(c_{i-1}) \big] = $$
$$ = \lim\limits_{||P|| \rightarrow 0} k \sum\limits_{i = 1}^{n} \big[ F(c_i) - F(c_{i-1}) \big] = \lim\limits_{||P|| \rightarrow 0} k \big[ F(b) - F(a) \big] = k \big[ F(b) - F(a) \big] $$

\newpage

#### Teorema 1.33

Los siguientes enunciados son equivalentes:

a. $\exists \lim\limits_{||P|| \rightarrow 0} S(P, g, F) = I < +\infty$

b. dado $\varepsilon > 0$, $\exists \delta$ tal que si $||P|| < \delta$ y $||Q|| < \delta$ se cumple que $| S(P, g, F) - S(Q, g, F)| < \varepsilon$

c. para toda sucesión de particiones $\{P_n\}_{n \in \mathbb{N}}$ de $[a,b]$ tal que $||P_n|| \xrightarrow{\enskip n \enskip} 0$ se cumple que $\lim\limits_{n \rightarrow +\infty} S(P, g, F) = I$

El teorema implíca que: $a \Leftrightarrow b \Leftrightarrow c$. Se prueba demostrando que $a \Leftrightarrow b$ y $a \Leftrightarrow c$, de donde se desprende, por transitiva, que $b \Leftrightarrow c$.

***

Parte 1: $a \Leftrightarrow b$, lo cual implíca probar que: si $a \Rightarrow b$, y si $b \Rightarrow a$

\vspace{0.5cm}

Parte 1.i) Si $\exists \lim\limits_{||P|| \rightarrow 0} S(P, g, F) = I < +\infty \Rightarrow$ dado $\varepsilon > 0$, $\exists \delta$ tal que si $||P|| < \delta$ y $||Q|| < \delta$ se cumple que $| S(P, g, F) - S(Q, g, F)| < \varepsilon$.

\vspace{0.5cm}

*Dem*: si $\exists \lim\limits_{||P|| \rightarrow 0} S_P = I \Rightarrow \exists P([a,b])$ con $||P|| < \delta$ tal que $|S_P - I | < \varepsilon$. Sea la partición $Q([a,b])$ tal que $||Q|| < \delta / 2$ entonces 
$$\begin{array}{r c l}
|S_{P} - I| & < & \varepsilon \\ \\
\underbrace{|S_{P} - I - S_Q + S_Q|}_{ \leq \underbrace{|S_P - S_Q|}_{\leq \varepsilon / 2} + |S_Q - I| } & < & \varepsilon
\end{array}$$

Por lo tanto, dado que $|S_P - S_Q| \leq \varepsilon / 2$, $|S_P - S_Q| < \varepsilon$.

\vspace{0.5cm}

Parte 1.ii) Dado $\varepsilon > 0$, $\exists \delta$ tal que si $||P|| < \delta$ y $||Q|| < \delta$ se cumple que $| S(P, g, F) - S(Q, g, F)| < \varepsilon \Rightarrow \exists \lim\limits_{||P|| \rightarrow 0} S(P, g, F) = I < +\infty$.

\vspace{0.5cm}

*Dem*:
$$|S(P,g,F) - S(Q,g,F)| < \varepsilon$$
$$|S(P,g,F) - I + I - S(Q,g,F)| < \varepsilon$$
$$|S(P,g,F) - I + I - S(Q,g,F)| < \underbrace{|S(P,g,F) - I|}_{\leq \varepsilon / 2} + \underbrace{|S(Q,g,F) - I|}_{\leq \varepsilon / 2} < \varepsilon$$

Por lo tanto, dado que $|S(P,g,F) - I| \leq \varepsilon / 2$, $\exists \lim\limits_{||P|| \rightarrow 0} S(P,g,F) = I$. Análogamente, dado que $|S(Q,g,F) - I| \leq \varepsilon / 2$, $\exists \lim\limits_{||Q|| \rightarrow 0 } S(Q,g,F) = I$.

Parte 2: $a \Leftrightarrow c$, lo cual implíca probar que: si $a \Rightarrow c$, y si $c \Rightarrow a$.

\vspace{0.5cm}

Parte 2.i) Si $\exists \lim\limits_{||P|| \rightarrow 0} S(P, g, F) = I < +\infty \Rightarrow$ para toda sucesión de particiones $\{P_n\}_{n \in \mathbb{N}}$ de $[a,b]$ tal que $||P_n|| \overset{n}{\rightarrow} 0$ se cumple que $\lim\limits_{n \rightarrow +\infty} S(P, g, F) = I$. Debemos tener en cuenta que $\lim\limits_{n \rightarrow +\infty} S(P, g, F) = I \Leftrightarrow \forall \varepsilon > 0$, $\exists \delta > 0$ tal que para toda partición $P$ del intervalo $[a,b]$ con $||P|| < \delta$, $|S(P, g, F) - I| < \varepsilon$.

\vspace{0.5cm}

*Dem*: si $\exists \lim\limits_{||P|| \rightarrow 0} S(P, g, F) \Rightarrow \forall \varepsilon > 0$, $\exists \delta > ||P||$ tal que $|S(P, g, F) - I| < \varepsilon$. Supongamos que existe una suciesión de particiones $\{P_n\}_{n \in \mathbb{N}}$ con $||P_n|| \overset{n}{\rightarrow} 0$. Esto implica que $\forall \delta^* > 0$, $\exists n_1 \leq n$ tal que $||P_n|| < \delta^*$. Si elegimos $\delta^* = \delta \Rightarrow$ por a) $\forall n \geq n_1$, se cumple que $|S(P, g, F) - I| < \varepsilon$.

\vspace{0.5cm}

Parte 2.ii) Si para toda sucesión de particiones $\{P_n\}_{n \in \mathbb{N}}$ de $[a,b]$ tal que $||P_n|| \overset{n}{\rightarrow} 0$ se cumple que $\lim\limits_{n \rightarrow +\infty} S(P, g, F) = I \Rightarrow \exists \lim\limits_{||P|| \rightarrow 0} S(P, g, F) = I < +\infty$.

\vspace{0.5cm}

*Dem*: Supongamos por absudo que $\exists \varepsilon > 0$ tal que $\exists P$ tal que $\forall \delta > ||P||$ se cunple que $|S(P, g, F) - I| \geq \varepsilon$. Elijo $\delta_n = ^1/_n$, entonces, para $\varepsilon > 0$, $\exists P_n$ tal que $\forall \delta_n = ^1/_n$ tal que $||P_n|| < \delta_n \Rightarrow |S(P, g, F) - I| \geq \varepsilon$. Por lo tanto, tengo definido una sucesión de particiones $\{P_n\}_{n \in \mathbb{N}}$ tal que $||P_n|| \overset{n}{\rightarrow} 0$ tal que $|S(P, g, F) - I| \geq \varepsilon$ lo cual es absurdo (porque partí del enunciado c).

#### Teorema 1.34

Si $g : [a,b] \rightarrow \mathbb{R}$ es continua y $F : [a,b] \rightarrow \mathbb{R}$ es monótona, entonces existe $\int\limits_a^b gdF$

*Dem*: demostrar que existe la integral implíca demostrar que el límite de las sumas parciales converge. 

#### Teorema 1.35

Si $g : [a,b] \rightarrow \mathbb{R}$ es continua y $F : [a,b] \rightarrow \mathbb{R}$ es monótona y derivable tal que $F'(x) = f(x)$ siendo $f$ integrable Riemann en $[a,b]$, entonces:
$$\int\limits_a^b g(x) d F(x) = \int\limits_a^b g(x) f(x) dx$$

*Dem*: Por el teorema del valor medio sabemos que:
$$ f(\xi_i) = \frac{ F(x_i) - F(x_{i-1}) }{ x_i - x_{i-1} } \Rightarrow f(\xi) [x_i - x_{i-1} ] = F(x_i) - F(x_{i-1}) \,\,\, \text{para todo } \xi \in [x_{i-1}, x_i]$$

Luego entonces,
$$\int\limits_a^b g(x) d F(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] =$$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) f(\xi_i) \big[ x_i - x_{i-1} \big] = \int\limits_a^b g(x) f(x) dx $$

#### Proposición 1.36

Si $g,h,F : [a,b] \rightarrow \mathbb{R}$ son tales que existen $\int\limits_a^b gdF$ y $\int\limits_a^b hdF$ entonces:

i. $\exists \int\limits_a^b (\alpha g + \beta h )dF \,\,\, \forall \alpha, \beta \in \mathbb{R}$
ii. $\int\limits_a^b (\alpha g + \beta h )dF = \alpha \int\limits_a^b gdF + \beta \int\limits_a^b hdF$

***

*Dem*:
$$\int\limits_a^b (\alpha g(x) + \beta h(x)) dF(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \big( \alpha g(\xi_i) + \beta h(\xi_i) \big) \big[ F(x_i) - F(x_{i-1}) \big] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \Big( \alpha g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] + \beta h(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] \Big) =$$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \alpha g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] + \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \beta h(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] = $$
$$= \alpha \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] + \beta \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} h(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] = $$
$$= \alpha \int\limits_a^b g(x) d F(x) + \beta \int\limits_a^b h(x) d F(x) = \alpha I_g + \beta I_h = I^*$$

\newpage

#### Proposición 1.37

Si $h,F,G : [a,b] \rightarrow \mathbb{R}$ son tales que existen $\int\limits_a^b hdF$ y $\int\limits_a^b hdG$ entonces:

i. $\exists \int\limits_a^b h d (\alpha F + \beta G) \,\,\, \forall \alpha, \beta \in \mathbb{R}$
ii. $\int\limits_a^b h d (\alpha F + \beta G) = \alpha \int\limits_a^b hdF + \beta \int\limits_a^b hdG$

*Dem*:
$$\int\limits_a^b h d (\alpha F + \beta G) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} h(x_i) \Big[ \alpha \big( F(x_i) - F(x_{i-1}) \big) + \beta \big( G(x_i) - G(x_{i-1}) \big) \Big] =$$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \alpha h(x_i) \big( F(x_i) - F(x_{i-1}) \big) + \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \beta h(x_i) \big( G(x_i) - G(x_{i-1}) \big) =$$
$$= \alpha \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} h(x_i) \big( F(x_i) - F(x_{i-1}) \big) + \beta \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} h(x_i) \big( G(x_i) - G(x_{i-1}) \big) =$$
$$= \alpha \int\limits_a^b hdF + \beta \int\limits_a^b h dG = \alpha I_F + \beta I_G = I^* $$


#### Proposición 1.38

Si $g,F : [a,b] \rightarrow \mathbb{R}$ son tales que existe $\int\limits_a^b gdF$, entonces:

i. para todo $c \in (a,b)$, $\exists \int\limits_a^c gdF$ y $\exists \int\limits_c^b gdF$
ii. $\int\limits_a^b gdF = \int\limits_a^c gdF + \int\limits_c^b gdF$

*Dem*: queremos demostrar que $\exists \int\limits_a^c gdF$. Por el teorema 1.33 sabemos que, dadas dos particiones $P$ y $Q$ tales que $||P|| \leq \delta$ y $||Q|| \leq \delta$, se cumple que $\big| S_P - S_Q \big| < \varepsilon$.

\vspace{0.3cm}

Construyo las siguientes dos particiones:

i. $P^*[a, \, b]$ tal que $||P^*|| < \delta$, $P^* = P$ en el intervalo $[a, \, c]$.

ii. $Q^*[a, \, b]$ tal que $||Q^*|| < \delta$, $Q^* = Q$ en el intervalo $[a, \, c]$.

iii. En el intervalo $[c, \, b]$, $P^*$ y $Q^*$ comparten los mismos límites.

Luego entonces,
$$\begin{array}{r c l}
\big| S_{P^*} - S_{Q^*} \big| & < & \varepsilon \\ \\
\big| S_P - S_Q \big| & < & \varepsilon \\ \\
\end{array}$$

Le demostración para la integral entre $c$ y $b$ es análoga. Que la suma de ambas es la integral en $[a, \, b]$ es una consequencia de la linealidad del límite y de la sumatoria.

#### Proposición 1.39

Si $g,F : [a,b] \rightarrow \mathbb{R}$ son tales que $\alpha \leq g(x) \leq \beta$ para todo $x \in [a,b]$, y $F$ es monótona no decreciente tal que existe $\int\limits_a^b gdF$ entonces:
$$\alpha \big( F(b) - F(a) \big) \leq \int\limits_a^b gdF \leq \beta \big( F(b) - F(a) \big) $$

#### Proposición 1.40

Si $g : [a,b] \rightarrow \mathbb{R}$ es continua, y $F : [a,b] \rightarrow \mathbb{R}$ es monótona no decreciete, entonces:
$$\left| \int\limits_a^b g(x) dF(x) \right| \leq \int\limits_a^b |g(x)| d F(x)$$


#### Proposición 1.41: Teorema del valor medio

Si $g,F : [a,b] \rightarrow \mathbb{R}$ son tales que $g$ es continua y $F$ es monótona creciente, entonces existe $c \in [a,b]$ tal que $\int\limits_a^b gdF = g(c) \big( F(b) - F(a) \big)$

*Dem*: por el teorema de Weierstrass sabemos que toda función continua tiene máximo ($M$) y mínimo ($m$) en un intervalo cerrado y acotado $[a,b]$. Por lo tanto:

i. $I = \int\limits_a^b gdF = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big(F(x_i) - F(x_{i-1}) \big) \leq \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} M \big(F(x_i) - F(x_{i-1}) \big) = M \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \big(F(x_i) - F(x_{i-1}) \big) = M \big( F(b) - F(a) \big)$

ii. $I = \int\limits_a^b gdF = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big(F(x_i) - F(x_{i-1}) \big) \geq \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} m \big(F(x_i) - F(x_{i-1}) \big) = m \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \big(F(x_i) - F(x_{i-1}) \big) = m \big( F(b) - F(a) \big)$

Por lo tanto, sabemos que:
$$m \big( F(b)-F(a) \big) \leq I \leq M \big( F(b)-F(a) \big) \Rightarrow m \leq \frac{1}{ F(b)-F(a) } \,\,  I \leq M$$

Luego, por el teorema de Darboux sabemos que $\exists c \in [a,b]$ tal que $g(c) = \frac{1}{ F(b)-F(a) } \,\,  I$. Por lo tanto, $I = g(c) \big(F(b) - F(a) \big)$.

\newpage

## Métodos de integración

#### Teorema 1.42: Integración por partes

Si $g,F : [a,b] \rightarrow \mathbb{R}$ son tales que existe $\int\limits_a^b gdF$, entonces:

i. $\exists \int\limits_a^b Fdg$
ii. $\int\limits_a^b Fdg = gF\Big|^b_a - \int\limits_a^b gdF$

#### Teorema 1.43: Cambio de variable

Si $g,F : [a,b] \rightarrow \mathbb{R}$ son tales que existe $\int\limits_a^b gdF$, y $h : [c,d] \rightarrow [a,b]$ es continua y biyectiva, entonces:

i. $\exists \int\limits_a^b (g \circ h) d(F \circ h)$
ii. $\int\limits_c^d g \big( h(t) \big) d F \big( h(t) \big) = \int\limits_a^b g(x) d F(x)$


## Aplicaciones a la teoría de la probabilidad

#### Proposición 1.44

Si $F_X$ es la función de distribución de una variable aleatoria $X$, entonces:
$$\int\limits_a^b dF_X(x) = P(a < X \leq b)$$

#### Proposición 1.45

Sea $X$ una variable aleatoria cuya función de distribución es $F_X$:

- Si su recorrido es $A = \{x_1, x_2, \ldots \}$ y $g : [a,b] \rightarrow \mathbb{R}$ es continua, entonces:
   $$\int\limits_a^b g(x) d F_X(x) = \sum\limits_{x \in (a,b] \cap A} g(x) p_X(x) = E \left( g(X) \mathbb{I}_{ \{ X \in (a,b] \} } \right) $$

- Si $X$ es absolutamente continua con densidad $f_X$ y $g : [a,b] \rightarrow \mathbb{R}$ es continua, entonces:
   $$\int\limits_a^b g(x) d F_X(x) = \int\limits_a^b g(x) f_X(x) dx = E \left( g(X) \mathbb{I}_{ \{ X \in (a,b] \} } \right) $$

De lo anterior se desprende que podemos definir la esperanza de una variable aleatoria $X$ con función de distribución $F_X$ como:

$$E(X) = \lim\limits_{\substack{a \rightarrow - \infty \\ b \rightarrow + \infty }} \int\limits_a^b x d F_X(x) = \int\limits_{-\infty}^{+\infty} x d F_X(x) $$

#### Ejercicio 1.46 (Ejercicio 5 del práctico 1)

Probar que si $F$ es una función de distribución, $a < b$ son puntos de continuidad de $F$, definimos:
$$\psi(x) = \left\{ 
\begin{array}{c c l}
0 & \text{si} & x < a, x > b \\
1/2 & \text{si} & x = a, x = b \\
1 & \text{si} & a < x < b
\end{array} \right.$$

entonces, $\int\limits_{-\infty}^{+\infty} \psi(x) dF(x) = F(b) - F(a)$

*Solución*: sea la partición $P = \{-z = c_0; \, \ldots; \, c_n = z\}$ tal que $a \in [c_{a-1}; \, c_a]$, $b \in [c_{b-1}; \, c_b]$ y $x_i \in [c_{i-1}; \, c_i]$. Luego entonces,
$$\int\limits_{-\infty}^{+\infty} \psi(x) dF(x) = \lim\limits_{z \rightarrow + \infty} \int\limits_{-z}^{z} \psi(x) dF(x) = \lim\limits_{z \rightarrow + \infty} \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \psi(x_i) \Big[ F(c_i) - F(c_{i-1})\Big] =$$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = a}^{b} \psi(x_i) \Big[ F(c_i) - F(c_{i-1})\Big] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \Bigg[ \underbrace{\psi(x_a)}_{\psi(a)} \Big[ \underbrace{ \underbrace{F(c_a)}_{F(a)} - \underbrace{F(c_{a-1})}_{F(a)} }_{= 0} \Big] + \sum\limits_{i = a+1}^{b-1} \psi(x_i) \Big[ F(c_i) - F(c_{i-1})\Big] + \underbrace{\psi(x_b)}_{\psi(b)} \Big[ \underbrace{\underbrace{F(c_b)}_{F(b)} - \underbrace{F(c_{b-1})}_{F(b)}}_{= 0} \Big] \Bigg] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = a+1}^{b-1} \underbrace{\psi(x_i)}_{= 1} \Big[ F(c_i) - F(c_{i-1})\Big] = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = a+1}^{b-1} \Big[ F(c_i) - F(c_{i-1})\Big] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \Big[ F(c_{b-1}) - F(c_{a+1})\Big] = F(b) - F(a)$$
donde la última igualdad se debe a que $c_{b-1} \xrightarrow{\enskip ||P|| \rightarrow 0 \enskip} b$ y $c_{a+1} \xrightarrow{\enskip ||P|| \rightarrow 0 \enskip} a$.
