---
title: "Práctico 1"
author: "Daniel Czarnievicz"
date: "2019"
output: pdf_document
header-includes:
   - \everymath{\displaystyle}
   - \usepackage{xcolor}
   - \usepackage[makeroom]{cancel}
   - \DeclareMathOperator*{\plim}{plim}
   - \usepackage{mathrsfs}
   - \usepackage{amsmath}
   - \usepackage{mathtools}
   - \newcommand{\equalexpl}[1]{\underset{\substack{\uparrow\\\\\mathrlap{\text{\hspace{-2em}#1}}}}{\approx}}
geometry: margin=1in
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejercicio 1

## Parte 1

Dado que se trata de una igualdad de conjuntos, debemos demostrar la doble inclusión.

\vspace{0.2cm}

Parte i: $\{ \omega \in \Omega / \omega \in A_n \text{ para infinitos valores de } n \} \subset \limsup\limits_{n} A_n$

Si $\omega$ pertenece a infinitos $A_n \Rightarrow \forall n$, $\exists n_0 \geq n / \omega \in A_{n_0}$. Luego si $\omega \in A_{n_0} \Rightarrow \omega \in \bigcup\limits_{k = n_0}^{+\infty} A_k \, \forall n$ dado que $n_0 \geq n$. Por lo tanto, $\omega \in \bigcap\limits_{n = 1}^{+\infty} \bigcup\limits_{k = n}^{+\infty} A_k = \limsup\limits_{n} A_n$

Parte ii: $\limsup\limits_{n} A_n \subset \{ \omega \in \Omega / \omega \in A_n \text{ para infinitos valores de } n \}$

Demostración por absurdo. Si $\omega$ pertenece a una cantidad finita de $A_n \Rightarrow \exists n / \forall n_1 \geq n$, $\omega \notin A_{n_1} \Rightarrow \omega \notin \bigcup\limits_{k = n_1}^{+\infty} A_k \Rightarrow \omega \notin \bigcap\limits_{n=1}^{+\infty} \bigcup\limits_{k = n_1}^{+\infty} A_k$

## Parte 2

Dado que se trata de una igualdad de conjuntos, debemos demostrar la doble inclusión.

\vspace{0.2cm}

Parte i: $\liminf\limits_{n} A_n \subset \{ \omega \in \Omega / \omega \in A_n \forall n \text{ salvo, a lo sumo, una cantidad finita de índices} \}$

$\exists n / \forall n_0 \geq n$, $\omega \in A_n \Rightarrow \omega \in \bigcap\limits_{k = n}^{+\infty} A_k \Rightarrow \omega \in \bigcup\limits_{n = 1}^{+\infty} \bigcap\limits_{n = k}^{+\infty} A_k$

Parte ii: $\{ \omega \in \Omega / \omega \in A_n \forall n \text{ salvo, a lo sumo, una cantidad finita de índices} \} \subset \liminf\limits_{n} A_n$

Si $\omega \in \bigcup\limits_{n = 1}^{+\infty} \bigcap\limits_{k = n}^{+\infty} A_k \Rightarrow \exists n_0 / \omega \in A_k \, \forall k \geq n_0$


## Parte 3

A continuación se demuestra que si $\omega$ pertenece al límite inferior, entonces debe existir un índice, $n_0$, a partir del cual $\omega$ pertenece a todos los $A_k$, dado que esa es la condición para pertenecer a la intersección de los conjuntos. Pero, en el enunciado 1 de la proposición se demostró que si $\omega$ pertenece a una cantidad infinita de índices, entonces pertenece al límite superior. 

Si $\omega \in \liminf\limits_{n} A_n \Rightarrow \exists n_0$ a partir del cual $\omega \in \bigcup\limits_{n=1}^{+\infty} \bigcap\limits_{k =n}^{+\infty} A_k \, \forall n \geq n_0 \Rightarrow \omega$ pertenece a una cantidad infinita de índices (todos ellos a partir de $n_0$) $\Rightarrow \omega \in \limsup\limits_{n} A_n$

## Parte 4

Veamos primero que la sucesión $B_n$ es decreciente. La misma está defiinida de la siguiente forma:
$$\begin{array}{l c c c c c c c c}
B_n & = & A_n & \cup & A_{n+1} & \cup & A_{n+2} & \cup & \ldots \\
B_{n+1} & = &  &  & A_{n+1} & \cup & A_{n+2} & \cup & \ldots \\
B_{n+2} & = &  &  &  &  & A_{n+2} & \cup & \ldots \\
\,\,\,\,\,\, \vdots & & & & & & & & 
\end{array}$$

Dado que cada vez unimos menos conjuntos, el conjunto resultante es "más chico", y por tanto, la sucesión es decreciente. Luego entonces,
$$\begin{array}{c c l c l}
P \left( \limsup\limits_{n} A_n \right) & = & P \left( \bigcap\limits_{n = 1}^{+\infty} \bigcup\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de límite superior} \\ \\
  & = & P \left( \bigcap\limits_{n = 1}^{+\infty} B_n \right) & & \text{por definición de $B_n$} \\ \\
  & = & \lim\limits_{n \rightarrow +\infty} P(B_n) & & \text{por continuidad de la probabilidad de una} \\
  &   &  & & \text{sucesión decreciente (ver prop 1.8/8)} \\ \\
  & = & \lim\limits_{n \rightarrow +\infty} P \left( \bigcup\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de $B_n$}
\end{array}$$

\newpage

## Parte 5

Veamos primero que la sucesión $B_n$ es creciente. La misma está defiinida de la siguiente forma:

$$\begin{array}{l c c c c c c c c}
B_n & = & A_n & \cap & A_{n+1} & \cap & A_{n+2} & \cap & \ldots \\
B_{n+1} & = &  &  & A_{n+1} & \cap & A_{n+2} & \cap & \ldots \\
B_{n+2} & = &  &  &  &  & A_{n+2} & \cap & \ldots \\
\,\,\,\,\,\, \vdots & & & & & & & & 
\end{array}$$
Dado que cada vez intersectamos menos conjuntos, el conjunto resultante es "más grande", y por tanto, la sucesión es creciente. Luego entonces,

$$\begin{array}{c c l c l}
P \left( \liminf\limits_{n} A_n \right) & = & P \left( \bigcup\limits_{n = 1}^{+\infty} \bigcap\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de límite inferior} \\ \\
  & = & P \left( \bigcup\limits_{n = 1}^{+\infty} B_n \right) & & \text{por definición de $B_n$} \\ \\
  & = & \lim\limits_{n \rightarrow +\infty} P(B_n) & & \text{por continuidad de la probabilidad de una } \\
  &   &  & & \text{sucesión creciente (ver prop 1.8/7)} \\ \\
  & = & \lim\limits_{n \rightarrow +\infty} P \left( \bigcap\limits_{k = n}^{+\infty} A_k \right) & & \text{por definición de $B_n$}
\end{array}$$

## Parte 6

Dado que se trata de una triple igualdad entre conjuntos, debemos demostrar dos de los pares de doble inclusiones, y el tercero se cumplirá por transitividad.

**Parte I**: $\liminf\limits_{n} A_n = \bigcup\limits_{n = 1}^{+\infty} A_n$

- Parte I.i: $\liminf\limits_{n} A_n \subset \bigcup\limits_{n = 1}^{+\infty} A_n$

Si $\omega \in \liminf\limits_{n} A_n \Rightarrow \omega \in \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k$. Pero si la sucesión es creciente, entonces $\bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k = \bigcup\limits_{n \in \mathbb{N}} A_n \Rightarrow \omega \in \bigcup\limits_{n \in \mathbb{N}} A_n \Rightarrow \liminf\limits_{n} A_n \subset \bigcup\limits_{n = 1}^{+\infty} A_n$.

\newpage

- Parte I.ii: $\bigcup\limits_{n = 1}^{+\infty} A_n \subset \liminf\limits_{n} A_n$

Si la sucesión es creciente, entonces $\bigcup\limits_{n \in \mathbb{N}} A_n = \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k$. Por lo tanto, $\forall \omega \in \bigcup\limits_{n \in \mathbb{N}} A_n$, $\omega \in \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k = \liminf_n A_n$. Por lo tanto, $\bigcup\limits_{n = 1}^{+\infty} A_n \subset \liminf\limits_{n} A_n$

\vspace{0.2cm}

**Parte II**: $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$

- Parte II.i: $\liminf\limits_{n} A_n \subset \limsup\limits_{n} A_n$

Ver parte 3 del ejercicio (no se requiere que la sucesión sea creciente).

- Parte II.ii: $\limsup\limits_{n} A_n \subset \liminf\limits_{n} A_n$

Si $\omega \in \limsup\limits_n A_n$ entonces $\omega$ pertenece a infinitos $A_n$ (ver demostración de parte 1). Pero dado que la sucesión es creciente, $\exists n_0$ tal que $\omega \in A_n \, \forall n \geq n_0$. Pero esto implica que $\omega \notin A_n$ solo para aquellos valores de $n < n_0$. Entonces $\omega$ no pertenece a una cantidad finita de índices. Por lo tanto, $\omega \in \liminf\limits_n A_n$ 

***

De lo anterior se desprende que $\liminf\limits_{n} A_n = \bigcup\limits_{n = 1}^{+\infty} A_n$ (parte I) y que $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$ (parte II). Por transitividad entonces $\bigcup\limits_{n = 1}^{+\infty} A_n = \limsup\limits_{n} A_n$, por lo que queda demostrado el teorema.

## Parte 7

Dado que se trata de una triple igualdad entre conjuntos, debemos demostrar dos de los pares de doble inclusiones, y el tercero se cumplirá por transitividad.

**Parte I**: $\limsup\limits_n A_n = \bigcap\limits_{n \in \mathbb{N}} A_n$

- Parte I.i: $\limsup\limits_n A_n \subset \bigcap\limits_{n \in \mathbb{N}} A_n$

Si $\omega \in \limsup\limits_{n} A_n \Rightarrow \omega \in \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k$. Pero si la sucesión es decreciente, entonces $\bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k = \bigcap\limits_{n \in \mathbb{N}} A_n \Rightarrow \omega \in \bigcap\limits_{n \in \mathbb{N}} A_n \Rightarrow \limsup\limits_{n} A_n \subset \bigcap\limits_{n = 1}^{+\infty} A_n$.

\newpage

- Parte I.ii: $\bigcap\limits_{n \in \mathbb{N}} A_n \subset \limsup\limits_n A_n$

Si la sucesión es decreciente, entonces $\bigcap\limits_{n \in \mathbb{N}} A_n = \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k$. Por lo tanto, $\forall \omega \in \bigcap\limits_{n \in \mathbb{N}} A_n$, $\omega \in \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k = \limsup_n A_n$. Por lo tanto, $\bigcap\limits_{n = 1}^{+\infty} A_n \subset \limsup\limits_{n} A_n$

\vspace{0.2cm}

**Parte II**: $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$

- Parte II.i: $\liminf\limits_{n} A_n \subset \limsup\limits_{n} A_n$

Ver parte 3 (no se requiere que la sucesión sea decreciente).

- Parte II.ii: $\limsup\limits_{n} A_n \subset \liminf\limits_{n} A_n$

Si $\omega \in \liminf\limits_n A_n$ entonces $\omega$ pertenece a todos los $A_n$ salvo, a lo sumo, a una cantidad finita de ellos (ver demostración de prop 1.11/2). Luego, si $\omega \in \limsup\limits_n A_n \Rightarrow \omega \in \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k$, pero si $\{A_n\}_{n \in \mathbb{N}}$ es decreciente, entonces $\omega \in \bigcap\limits_{n \in \mathbb{N}} A_n \Rightarrow$ por definición de intersección, $\omega \in A_n \, \forall n \Rightarrow \omega \in \liminf\limits_n A_n$

***

De lo anterior se desprende que $\limsup\limits_{n} A_n = \bigcap\limits_{n = 1}^{+\infty} A_n$ (parte I) y que $\liminf\limits_{n} A_n = \limsup\limits_{n} A_n$ (parte II). Por transitividad entonces $\bigcap\limits_{n = 1}^{+\infty} A_n = \liminf\limits_{n} A_n$, por lo que queda demostrado el teorema.

\newpage

## Parte 8

Debemos demostrar tres de las cuatro desigualdades. La última queda demostrada por transitividad.

**Parte I**: $P \left( \liminf\limits_{n} A_n \right) \leq \liminf\limits_{n} P(A_n)$

$$\begin{array}{c c l c l}
P \left( \liminf\limits_{n} A_n \right) & = & P \left( \bigcup\limits_{n \in \mathbb{N}} \bigcap\limits_{k \geq n} A_k \right) & & \text{por definición de límite inferior} \\ \\
  & = & P \left( \bigcup\limits_{n \in \mathbb{N}} B_n \right) & & \text{definiendo a $B_n = \bigcap\limits_{k \geq n} A_k$} \\ \\
  & = & \lim\limits_n P(B_n) & & \text{por ser $B_n$ creciente} \\ \\
  & = & \lim\limits_n P \left( \bigcap\limits_{k \geq n} A_k \right) & & \text{por definición de $B_n$} \\ \\
  & = & \liminf\limits_n P \left( \bigcap\limits_{k \geq n} A_k \right) & & \text{por ser el primero el límite de una sucesión} \\ \\
  & \leq & \liminf\limits_n P(A_k) \,\,\, \forall k \geq n & & \text{por definición de intersecsión}
\end{array}$$

**Parte II**: $\liminf\limits_{n} P(A_n) \leq \limsup\limits_{n} P(A_n)$

En este caso estamos hablando del límite inferior y del límite superior de una sucesión real, los cuales se definen como:

- $\liminf\limits_n P(A_n) = \lim\limits_n \left[ \inf\limits_{k \geq n} P(A_n) \right]$
- $\limsup\limits_n P(A_n) = \lim\limits_n \left[ \sup\limits_{k \geq n} P(A_n) \right]$

Por lo tanto, $\liminf\limits_n P(A_n) \leq \limsup\limits_n P(A_n)$

\newpage

**Parte III**: $\limsup\limits_{n} P(A_n) \leq P \left( \limsup\limits_{n} A_n \right)$

$$\begin{array}{c c l c l}
P \left( \limsup\limits_{n} A_n \right) & = & P \left( \bigcap\limits_{n \in \mathbb{N}} \bigcup\limits_{k \geq n} A_k \right) & & \text{por definición de límite superior} \\ \\
  & = & P \left( \bigcap\limits_{n \in \mathbb{N}} B_n \right) & & \text{definiendo a $B_n = \bigcup\limits_{k \geq n} A_k$} \\ \\
  & = & \lim\limits_n P(B_n) & & \text{por ser $B_n$ decreciente} \\ \\
  & = & \lim\limits_n P \left( \bigcup\limits_{k \geq n} A_k \right) & & \text{por definición de $B_n$} \\ \\
  & = & \limsup\limits_n P \left( \bigcup\limits_{k \geq n} A_k \right) & & \text{por ser el primero el límite de una sucesión} \\ \\
  & \geq & \limsup\limits_n P(A_k) \, \forall k \geq n & & \text{por definición de unión}
\end{array}$$

# Ejercicio 2

Por el teorema del valor medio sabemos que:
$$ f(\xi_i) = \frac{ F(x_i) - F(x_{i-1}) }{ x_i - x_{i-1} } \Rightarrow f(\xi) [x_i - x_{i-1} ] = F(x_i) - F(x_{i-1}) \,\,\, \text{para todo } \xi \in [x_{i-1}, x_i]$$

Luego entonces,
$$\int\limits_a^b g(x) d F(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] =$$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) f(\xi_i) \big[ x_i - x_{i-1} \big] = \int\limits_a^b g(x) f(x) dx $$

\newpage

# Ejercicio 3

$$\int\limits_a^b (\alpha g(x) + \beta h(x)) dF(x) = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \big( \alpha g(\xi_i) + \beta h(\xi_i) \big) \big[ F(x_i) - F(x_{i-1}) \big] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \Big( \alpha g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] + \beta h(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] \Big) =$$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \alpha g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] + \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \beta h(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] = $$
$$= \alpha \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] + \beta \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} h(\xi_i) \big[ F(x_i) - F(x_{i-1}) \big] = $$
$$= \alpha \int\limits_a^b g(x) d F(x) + \beta \int\limits_a^b h(x) d F(x) = \alpha I_g + \beta I_h = I^*$$

# Ejercicio 4

Por el teorema de Weierstrass sabemos que toda función continua tiene máximo ($M$) y mínimo ($m$) en un intervalo cerrado y acotado $[a,b]$. Por lo tanto:

i. $I = \int\limits_a^b gdF = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big(F(x_i) - F(x_{i-1}) \big) \leq \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} M \big(F(x_i) - F(x_{i-1}) \big) = M \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \big(F(x_i) - F(x_{i-1}) \big) = M \big( F(b) - F(a) \big)$

ii. $I = \int\limits_a^b gdF = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \big(F(x_i) - F(x_{i-1}) \big) \geq \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} m \big(F(x_i) - F(x_{i-1}) \big) = m \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \big(F(x_i) - F(x_{i-1}) \big) = m \big( F(b) - F(a) \big)$

Por lo tanto, sabemos que:
$$m \big( F(b)-F(a) \big) \leq I \leq M \big( F(b)-F(a) \big) \Rightarrow m \leq \frac{1}{ F(b)-F(a) } \,\,  I \leq M$$

Luego, por el teorema de Darboux sabemos que $\exists c \in [a,b]$ tal que $g(c) = \frac{1}{ F(b)-F(a) } \,\,  I$. Por lo tanto, $I = g(c) \big(F(b) - F(a) \big)$.

# Ejercicio 5

Sea la partición $P = \{-z = c_0; \, \ldots; \, c_n = z\}$ tal que $a \in [c_{a-1}; \, c_a]$, $b \in [c_{b-1}; \, c_b]$ y $x_i \in [c_{i-1}; \, c_i]$. Luego entonces,
$$\int\limits_{-\infty}^{+\infty} \psi(x) dF(x) = \lim\limits_{z \rightarrow + \infty} \int\limits_{-z}^{z} \psi(x) dF(x) = \lim\limits_{z \rightarrow + \infty} \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} \psi(x_i) \Big[ F(c_i) - F(c_{i-1})\Big] =$$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = a}^{b} \psi(x_i) \Big[ F(c_i) - F(c_{i-1})\Big] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \Bigg[ \underbrace{\psi(x_a)}_{\psi(a)} \Big[ \underbrace{ \underbrace{F(c_a)}_{F(a)} - \underbrace{F(c_{a-1})}_{F(a)} }_{= 0} \Big] + \sum\limits_{i = a+1}^{b-1} \psi(x_i) \Big[ F(c_i) - F(c_{i-1})\Big] + \underbrace{\psi(x_b)}_{\psi(b)} \Big[ \underbrace{\underbrace{F(c_b)}_{F(b)} - \underbrace{F(c_{b-1})}_{F(b)}}_{= 0} \Big] \Bigg] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = a+1}^{b-1} \underbrace{\psi(x_i)}_{= 1} \Big[ F(c_i) - F(c_{i-1})\Big] = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = a+1}^{b-1} \Big[ F(c_i) - F(c_{i-1})\Big] = $$
$$= \lim\limits_{||P|| \rightarrow 0} \Big[ F(c_{b-1}) - F(c_{a+1})\Big] = F(b) - F(a)$$
donde la última igualdad se debe a que $c_{b-1} \xrightarrow{\enskip ||P|| \rightarrow 0 \enskip} b$ y $c_{a+1} \xrightarrow{\enskip ||P|| \rightarrow 0 \enskip} a$.

# Ejercicio 6

## Parte a

Queremos demostrar que $\exists \int\limits_a^c gdF$. Por el teorema 1.33 sabemos que, dadas dos particiones $P$ y $Q$ tales que $||P|| \leq \delta$ y $||Q|| \leq \delta$, se cumple que $\big| S_P - S_Q \big| < \varepsilon$.

\vspace{0.3cm}

Construyo las siguientes dos particiones:

i. $P^*[a, \, b]$ tal que $||P^*|| < \delta$, $P^* = P$ en el intervalo $[a, \, c]$.

ii. $Q^*[a, \, b]$ tal que $||Q^*|| < \delta$, $Q^* = Q$ en el intervalo $[a, \, c]$.

iii. En el intervalo $[c, \, b]$, $P^*$ y $Q^*$ comparten los mismos límites.

Luego entonces,
$$\begin{array}{r c l}
\big| S_{P^*} - S_{Q^*} \big| & < & \varepsilon \\ \\
\big| S_P - S_Q \big| & < & \varepsilon \\ \\
\end{array}$$

## Parte b

Sean $g(x) = \mathbb{I}_{(c, \, b]}$ y $f(x) = \mathbb{I}_{[c, \, b]}$, entonces:

1. $\int\limits_a^c gdF = 0$ dado que está fuera del intervalo.  

2. $\int\limits_c^b gdF = 0$ dado que $F$ siempre vale 1.  

3. $\int\limits_a^b gdF = \lim\limits_{||P|| \rightarrow 0} \sum\limits_{i = 1}^{n} g(\xi_i) \Big[ F(c_i) - F(c_{i-1}) \Big]$  

Luego, sea $c \in [c_j, \, c_{j+1}]$. Si $\xi_i \in [c_j, \, c]$ entonces:
$$\lim\limits_{||P|| \rightarrow 0} g(\xi_i) \Big[ \underbrace{F(c_j)}_{= 0} - \underbrace{F(c)}_{= 1} \Big] = \lim\limits_{||P|| \rightarrow 0} g(\xi_i) = 0$$
Si, en cambio, $\xi_i \in [c, \, c_{j+1}]$, entonces:
$$\lim\limits_{||P|| \rightarrow 0} g(\xi_i) \Big[ \underbrace{F(c_j)}_{= 0} - \underbrace{F(c)}_{= 1} \Big] = \lim\limits_{||P|| \rightarrow 0} g(\xi_i) = 1$$

Dado que los límites por derecha e izquierda de $c$ no coinciden, entonces no existe dicho límite, y por tanto no existe la integral.
