---
title: "Práctico 5"
author: "Daniel Czarnievicz"
date: "2019"
output: pdf_document
header-includes:
   - \everymath{\displaystyle}
   - \usepackage[spanish]{babel}
   - \usepackage{xcolor}
   - \usepackage[makeroom]{cancel}
   - \DeclareMathOperator*{\plim}{plim}
   - \usepackage{mathrsfs}
   - \usepackage{amsmath}
   - \usepackage{mathtools}
   - \newcommand{\equalexpl}[1]{\underset{\substack{\uparrow\\\\\mathrlap{\text{\hspace{-2em}#1}}}}{\approx}}
   - \DeclareMathOperator{\E}{\mathbf{E}}
   - \DeclareMathOperator{\V}{\mathbf{V}}
geometry: margin=1in
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejercicio 1

## Parte a

Sea $X$ una variable aleatoria con distribución $\text{Unif}(-1, 1)$. La función característica de $X$ será entonces $\varphi_X(t) = \frac{\sin t }{t}$. Luego, por el teorema de inversión sabemos que:

$$f_X(x) = \frac{1}{2 \pi} \int\limits_{-\infty}^{+\infty} e^{-itx} \varphi_X (t) dt$$

Por lo tanto, resolver la integral propuesta implíca resolver $f_X(0)$. Pero dado que $X \sim \text{Unif}(-1, 1)$, sabemos que $f_X(x) = 1/2$ para todo $x \in [-1, 1]$. Por lo tanto,

$$f_X(0) = \frac{1}{2 \pi} \int\limits_{-\infty}^{+\infty} e^{-it(0)} \varphi_X (t) dt = \frac{1}{2 \pi} \int\limits_{-\infty}^{+\infty} \varphi_X (t) dt = \frac{1}{2} \Rightarrow \int\limits_{-\infty}^{+\infty} \varphi_X (t) dt = \pi$$

## Parte b

Consideremos ahora una segunda variable aleatoria $Y$ independiente de $X$ pero con la misma distribución. Por la propiedad 3.3/4 sabemos que $\varphi_{X + Y}(t) = \varphi_X(t) \, \varphi_Y(t)$. Pero dado que ambas variables tiene la misma distribución, la función característica de su suma será: 
$$\varphi_Z(t) = \varphi_{X + Y}(t) = \varphi^2_X(t) = \left( \frac{\sin t}{t} \right)^2$$

Por otro lado, que $X$ e $Y$ tienen distibución $\text{Unif}(-1, 1)$, $Z = X + Y \sim \text{Triag}(-2, 2)$. Por lo tanto, tenemos que:

$$\left. \begin{array}{lcc}
f_Z(0) = \frac{1}{2} \\
f_Z(0) = \frac{1}{2 \pi} \int\limits_{-\infty}^{+\infty} e^{-it(0)} \, \varphi_Z(t) dt
\end{array} \right\} \Rightarrow \int\limits_{-\infty}^{+\infty} \varphi_Z(t) dt = \pi$$


# Ejercicio 2

Primero hallamos la función característica de una variable con distribución exponencial:

$$\varphi_X(t) = \E \big( e^{itX} \big) = \int\limits_0^{+\infty} e^{itx} \lambda e^{-\lambda x} dx = \lambda \int\limits_0^{+\infty} e^{x(it - \lambda)} dx = \lambda \left[ \left. \frac{ e^{x(it - \lambda)} }{ it - \lambda } \right|_{x = 0}^{x \rightarrow + \infty} \right] = \frac{ - \lambda }{ it - \lambda } = \frac{ \lambda }{ \lambda - it }$$

Antes de proceder a integrar la función característica, conviene multiplicar por su conjugado de forma de lograr una expresión que no tenga a la constante imaginaria $i$ en el denominador.

$$\frac{\lambda}{\lambda - it} \times \frac{\lambda + it}{\lambda + it} = \frac{ \lambda^2 + \lambda i t }{ \lambda^2 + t^2 } = \frac{\lambda^2}{\lambda^2 + t^2} + \frac{\lambda t}{ \lambda^2 + t^2 } \,\, i$$

Luego procedemos a integrar el módulo de $\varphi_X$ de la siguiente forma:

$$\int\limits_{-\infty}^{+\infty} \big| \varphi_X (t) \big| dt = \int\limits_{-\infty}^{+\infty} \left| \frac{\lambda^2}{\lambda^2 + t^2} + \frac{\lambda t}{ \lambda^2 + t^2 } \,\, i \right| dt \leq \int\limits_{-\infty}^{+\infty} \left| \frac{\lambda^2}{\lambda^2 + t^2} \right| + \left| \frac{\lambda t}{ \lambda^2 + t^2 } \,\, i \right| dt = $$
$$ = \int\limits_{-\infty}^{+\infty} \left| \frac{\lambda^2}{\lambda^2 + t^2} \right| dt + \int\limits_{-\infty}^{+\infty} |i| \left| \frac{\lambda t}{ \lambda^2 + t^2 } \right| dt = \int\limits_{-\infty}^{+\infty} \left| \frac{\lambda^2}{\lambda^2 + t^2} \right| dt + \int\limits_{-\infty}^{+\infty} \left| \frac{\lambda t}{ \lambda^2 + t^2 } \right| dt$$

Dado que todas las cantidades son positivas, no es necesario seguir trabajando con el valor absoluto. Por lo tanto:

$$\int\limits_{-\infty}^{+\infty} \left| \frac{\lambda^2}{\lambda^2 + t^2} \right| dt + \int\limits_{-\infty}^{+\infty} \left| \frac{\lambda t}{ \lambda^2 + t^2 } \right| dt = \int\limits_{-\infty}^{+\infty} \frac{\lambda^2}{\lambda^2 + t^2} dt + \int\limits_{-\infty}^{+\infty} \frac{\lambda t}{ \lambda^2 + t^2 } dt =$$
$$= \sqrt{\lambda} \left. \tan^{-1}  \left( \frac{t}{\sqrt{\lambda}} \right) \right|_{-\infty}^{+\infty} + \left. \frac{\lambda}{2} \, \ln| \lambda^2 + t^2| \right|_{-\infty}^{+\infty} = +\infty$$

\newpage

# Ejercicio 3

## Parte a

$$\varphi_X(t) = \E \big( e^{itX} \big) = \int\limits_{-\infty}^{+\infty} e^{itx} \frac{1}{2} e^{-|x|} dx = $$
$$= \frac{1}{2} \int\limits_{-\infty}^{0} e^{x(it + 1)} dx + \frac{1}{2} \int\limits_{0}^{+\infty} e^{x(it - 1)} dx = \frac{1}{2} \left. \frac{ e^{x(it + 1)} }{ it + 1 } \right|_{-\infty}^{0} + \frac{1}{2} \left. \frac{ e^{x(it - 1)} }{ it - 1 } \right|_{0}^{+\infty} =$$
$$= \frac{1}{2(it + 1)} - \lim\limits_{x \rightarrow - \infty} \frac{e^{x(it + 1)}}{2(it + 1)} + \lim\limits_{x \rightarrow + \infty} \frac{e^{x(it - 1)}}{2(it - 1)} - \frac{1}{2(it - 1)} =$$
$$= \frac{1}{2(it + 1)} - \lim\limits_{x \rightarrow - \infty} \underbrace{ \frac{ \overbrace{e^x}^{\rightarrow 0} \big( \overbrace{\cos(tx)}^{\text{acot}} + i \overbrace{\sin(tx)}^{\text{acot}} \big) }{2(it + 1)} }_{\rightarrow 0} + \lim\limits_{x \rightarrow + \infty} \frac{e^{x(it - 1)}}{2(it - 1)} - \frac{1}{2(it - 1)} =$$
$$= \frac{1}{2(it + 1)} + \lim\limits_{x \rightarrow + \infty} \underbrace{ \frac{ \overbrace{e^{-x}}^{\rightarrow 0} \big( \overbrace{\cos(tx)}^{\text{acot}} + i \overbrace{\sin(tx)}^{\text{acot}} \big) }{2(it - 1)} }_{\rightarrow 0} - \frac{1}{2(it - 1)} =$$
$$= \frac{1}{2(it + 1)} - \frac{1}{2(it - 1)} = \frac{ it + 1 - it + 1 }{ 2 (it + 1)(it - 1) } = \frac{1}{1 + t^2}$$

\newpage

## Parte b

Antes de utilizar el enunciado 2 del teorema de inversión debemos verificar que estamos en las condiciones del mismo:
$$\int\limits_{-\infty}^{+\infty} |\varphi_X(t)| dt = \int\limits_{-\infty}^{+\infty} \left| \frac{1}{1 + t^2} \right| dt = \arctan(t) \Big|_{-\infty}^{+\infty} = \frac{\pi}{2} - \left( - \frac{\pi}{2} \right) = \pi < \infty$$

Luego entonces:
$$\begin{array}{r c l}
f_x(x) & = & \frac{1}{2\pi} \int\limits_{-\infty}^{+\infty} e^{itx} \varphi_X(t) dt \\
   & = & \frac{1}{2\pi} \int\limits_{-\infty}^{+\infty} e^{itx} \frac{1}{1 + t^2} dt \\
   & = & \frac{1}{2\pi} \int\limits_{-\infty}^{+\infty} \big( \cos(-tx) + i \sin(-tx) \big) \frac{1}{1 + t^2} dt \\
   & = & \frac{1}{2\pi} \int\limits_{-\infty}^{+\infty} \frac{ \cos(tx) }{ 1 + t^2} dt - i \int\limits_{-\infty}^{+\infty} \frac{ \sin(-tx) }{1 + t^2} dt \\
   & = & \frac{1}{2 \pi} \int\limits_{-\infty}^{+\infty} \frac{ \cos(tx) }{ 1 + t^2} dt \\
   & = & \frac{1}{2\pi} \pi e^{-|x|} \\ \\
   & = & \frac{1}{2} e^{-|x|} \\
\end{array}$$

## Parte c

$$\varphi_X(t) = \E \big( e^{itX} \big) = \int\limits_{-\infty}^{+\infty} e^{itx} \frac{1}{ \pi(1 + x^2) } dx = \frac{1}{\pi} \int\limits_{-\infty}^{+\infty} \frac{ \cos(tx) + i \sin(tx) }{ 1 + x^2 } dx = \frac{1}{\pi} \int\limits_{-\infty}^{+\infty} \frac{ \cos(tx) }{ 1 + x^2 } dx = e^{-|t|}$$

# Ejercicio 4

$$\varphi_{\bar{X}_n}(t) = \E \left( e^{it\bar{X}_n} \right) = \E \left( e^{i (t/n) X_1 } \right) \ldots \E \left( e^{i (t/n) X_n } \right) = \left[ \varphi_X (^t\!/\!_n) \right]^n = \left[ e^{-|t/n|} \right]^n = e^{-n|t/n|} = e^{-|t|} $$

Por lo tanto, $\bar{X}_n \sim \text{Cauchy}(0, 1)$.

# Ejercicio 5

Sea $U \sim \text{Unif}(0, 1) \Rightarrow \varphi_U : \mathbb{R} \rightarrow \mathbb{C} / \varphi_U (t) = \frac{e^{it} - 1}{it}$.

Luego sea $Z = X - Y$ donde $X$ e $Y$ son iid. Su función característica será:

$$\varphi_Z(t) = \varphi_{X - Y}(t) = \varphi_X(t) \varphi_{-Y}(t) = \varphi_X(t) \varphi_Y(-t) = \varphi_X \,\, \overline{\varphi_X (-t)} = \left| \varphi_X(t) \right|^2 \in \mathbb{R}$$

Por lo tanto, no es posible encontrar dos variables iid tales que su resta tenga distribución $\text{Unif}(0, 1)$.

# Ejercicio 6

$$\begin{array}{rcl}
\varphi_{ (X + Y)^s } & = & \E \left( e^{it(X + Y)^s} \right) \\
   & = & \E \left( e^{it(X + Y - X' - Y')} \right) \\
   & = & \E \left( e^{it(X - X') + it(Y - Y')} \right) \\
   & = & \E \left( e^{ it(X - X') } \right) \, \E \left( e^{ it(Y - Y') } \right) \\
   & = & \varphi_{X^s}(t) \, \varphi_{Y^s}(t) \\
   & = & \varphi_{ X^s + Y^s } (t)
\end{array}$$

Por lo tanto, $(X + Y)^s \overset{d}{=} X^s + Y^s$.