---
title: "Práctico 4"
author: "Daniel Czarnievicz"
date: "2019"
output: pdf_document
header-includes:
   - \everymath{\displaystyle}
   - \usepackage[spanish]{babel}
   - \usepackage{xcolor}
   - \usepackage[makeroom]{cancel}
   - \DeclareMathOperator*{\plim}{plim}
   - \usepackage{mathrsfs}
   - \usepackage{amsmath}
   - \usepackage{mathtools}
   - \newcommand{\equalexpl}[1]{\underset{\substack{\uparrow\\\\\mathrlap{\text{\hspace{-2em}#1}}}}{\approx}}
   - \DeclareMathOperator{\E}{\mathbf{E}}
   - \DeclareMathOperator{\V}{\mathbf{Var}}
geometry: margin=1in
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Ejercicio 1

## a) Calcular la parte real e imaginaria de $\frac{1}{a + bi}$, y $(a + bi)^2$

$$\frac{1}{a + bi} = \frac{1}{a + bi} \times \frac{a - bi}{a - bi} = \frac{a - bi}{ a^2 - abi + bia -b^2 i^2 } = \frac{a - bi}{ a^2 + b^2 } = \frac{a}{a^2 + b^2} - \frac{b}{a^2 + b^2} \, i$$

$$(a + bi)^2 = a^2 + 2abi + b^2 i^2 = a^2 - b^2 + 2abi$$

## b) Probar que $\overline{z_1 z_2} = \overline{z_1} \, \overline{z_2}$ para todo $z_1$, $z_2 \in \mathbb{C}$

$$\begin{array}{r c l}
\overline{z_1 \, z_2} & = & \overline{ (a + bi)(c + di) } \\
                      & = & \overline{ ac + adi + bic + bd i^2 } \\
                      & = & \overline{ (ac - bd) + (ad + bc)i } \\
                      & = & (ac - bd) - (ad + bc)i \\
                      & = & ac - bd - adi - bci \\
                      & = & ac + bd i^2 - adi - bci \\
                      & = & ac + bi di - adi - bci \\
                      & = & ac - adi + bi di - bci \\
                      & = & a (c - di) + bi (di - c) \\
                      & = & a (c - di) - bi (c - di) \\
                      & = & (a - bi) (c - di) \\
                      & = & \overline{z_1} \, \overline{z_2}
\end{array}$$

## c) Probar que $\overline{\overline{z}} = z$ para todo $z \in \mathbb{C}$

$$\overline{\overline{z}} = \overline{\overline{a + bi}} = \overline{a - bi} = a + bi = z$$

## d) Probar que $|z_1 + z_2| \leq |z_1| + |z_2|$ para todo $z_1$ y $z_2 \in 0mathbb{C}$

$$\begin{array}{r c l}
|z_1 + z_2|^2 & = & (z_1 + z_2) \overline{(z_1 + z_2)} \\
              & = & (z_1 + z_2) (\overline{z_1} + \overline{z_2}) \\
              & = & z_1 \overline{z_1} + z_1 \overline{z_2} + z_2 \overline{z_1} + z_2 \overline{z_2} \\
              & = & |z_1|^2 + z_1 \overline{z_2} + \overline{\overline{z_2 \overline{z_1}}} + |z_2|^2 \\
              & = & |z_1|^2 + z_1 \overline{z_2} + \overline{\overline{z_2} z_1} + |z_2|^2 \\
              & = & |z_1|^2 + 2 \mathfrak{R}(z_1 \overline{z_2}) + |z_2|^2 \\
              & \leq & |z_1|^2 + 2 | z_1 \overline{z_2} | + |z_2|^2 \\
              & = & |z_1|^2 + 2 |z_1| \, |\overline{z_2}| + |z_2|^2 \\
              & = & |z_1|^2 + 2 |z_1| \, |z_2| + |z_2|^2 \\
              & = & \big( |z_1| + |z_2| \big)^2
\end{array}$$

Por lo tanto, hallamos que $|z_1 + z_2|^2 \leq \big( |z_1| + |z_2| \big)^2$ de donde se desprende que:
$$|z_1 + z_2| \leq|z_1| + |z_2|$$

## e) Probar que $|z_1 \, z_2| = |z_1| \, |z_2|$ para todo $z_1$ y $z_2 \in \mathbb{C}$

$$\begin{array}{r c l}
|z_1 \, z_2| & = & |(a + bi)(c + di)| \\
             & = & |ac + adi + bic + bdi^2| \\
             & = & |(ac - bd) + (bc+ ad)i | \\
             & = & \sqrt{ (ac - bd)^2 + (bc + ad)^2 } \\
             & = & \sqrt{ (ac)^2 - 2abcd + (bd)^2 + (bc)^2 + 2abcd + (ad)^2 } \\
             & = & \sqrt{ (ac)^2 + (bd)^2 + (bc)^2 + (ad)^2 } \\
             & = & \sqrt{  a^2c^2 + b^2d^2 + b^2c^2 + a^2d^2 } \\
             & = & \sqrt{ a^2 (c^2 + d^2) + b^2 (c^2 + d^2) } \\
             & = & \sqrt{ (a^2 + b^2)(c^2 + d^2) } \\
             & = & |z_1| \, |z_2|
\end{array}$$

\newpage

# Ejercicio 2

Recordar que:

- $e^{itx} = \cos(tx) + i \sin(tx)$  
- $\sin(x)$ es impar, por lo tanto, $\sin(x) = - \sin(-x)$, y $\int\limits_{\mathbb{R}} \sin(x) dx = 0$. 
- $\cos(x)$ es par, por lo tanto, $\cos(x) = \cos(-x)$, y $\int\limits_{\mathbb{R}} \cos(x) dx = 2 \int\limits_0^{+\infty} \cos(x) dx$. 

## a) $X \sim \text{Unif}(-a, a)$ con $a \in \mathbb{R}$

$$\varphi_X(t) = \E \big( e^{itX} \big) = \int\limits_{-a}^{a} e^{itx} \frac{1}{2a} dx = \frac{1}{2a} \int\limits_{-a}^{a} e^{itx} dx = \frac{1}{2a} \int\limits_{-a}^{a} \big( \cos(tx) - i \sin(tx) \big) dx = $$
$$= \frac{1}{2a} \int\limits_{-a}^{a} \cos(tx) dx - \frac{i}{2a} \underbrace{ \int\limits_{-a}^{a} \sin(tx) dx }_{ \substack{ = 0, \text{ por ser seno} \\ \text{ función impar} } } = \frac{1}{a} \int\limits_{0}^{a} \cos(tx) dx = \frac{1}{a} \left( \left. \frac{ \sin(tx) }{ t } \right|_{0}^{a} \right) = \frac{ \sin(ta) }{ ta }$$

## b) $X \sim \text{Pois}(\lambda)$

$$\varphi_X (t) = \E \big( e^{itX} \big) = \sum\limits_{x = 0}^{+\infty} e^{itx} \frac{ e^{-\lambda} \lambda^{x} }{ x! } = e^{-\lambda} \sum\limits_{x = 0}^{+\infty} \frac{ (e^{it} \lambda)^{x} }{ x! } = \exp\big\{ - \lambda + e^{it} \lambda \big\} = \exp\big\{ \lambda ( e^{it} - 1) \big\} $$

## c) $X \sim \text{Bin}(n, p)$

$$\varphi_X(t) = \E \big( e^{itX} \big) = \sum\limits_{x = 0}^{n} e^{itx} {{n}\choose{x}} p^x (1 - p)^{n - x} = \sum\limits_{x = 0}^{n} {{n}\choose{x}} \big( e^{it} p \big)^x (1 - p)^{n - x} = \big( e^{it} p + 1 - p \big)^n$$

\newpage

## d) $X \sim \text{N}(\mu, \sigma^2)$

Primero hallamos la función característica de una variable aleatoria $Y$ con distribución $\text{Normal}(0, 1)$, y luego utilizamos la propiedad 3 (prop 3.3) para hallar la de una $\text{Normal}(\mu, \sigma^2)$.

$$\varphi_Y(t) = \E \big[ e^{ity} \big] = \int\limits_{-\infty}^{+\infty} e^{ity} \, \phi_Y(y) dy = \int\limits_{-\infty}^{+\infty} e^{ity} \, \frac{1}{ \sqrt{2 \pi} } e^{-y^2 / 2} dx$$
$$\frac{ \partial }{ \partial t } \varphi_Y (t) = \frac{ \partial }{\partial t} \int\limits_{-\infty}^{+\infty} e^{ity} \frac{1}{ \sqrt{2 \pi} } \, e^{- y^2 / 2} dy = \int\limits_{-\infty}^{+\infty} \left( \frac{ \partial }{\partial t} \, e^{ity} \right) \frac{1}{ \sqrt{2 \pi} } \, e^{- y^2 / 2} dy =$$
$$= \int\limits_{-\infty}^{+\infty} i x \, e^{ity} \frac{1}{ \sqrt{2 \pi} } \, e^{- y^2 / 2} dy = -\frac{ i }{ \sqrt{2 \pi} } \int\limits_{-\infty}^{+\infty} e^{ity} \, (-y) \, e^{- y^2 / 2} dy$$

Podemos luego entonces aplicar integración por partes donde $g(y) = e^{ity} \Rightarrow g'(y) = it \, e^{ity}$, y $f'(y) = (-y) \, e^{- y^2 / 2} \Rightarrow f(y) = e^{-y^2 / 2}$ y obtenemos que:
$$\frac{ \partial }{ \partial t } \varphi_Y (t) = i \left[ \frac{ \big( -e^{-y^2 / 2} \big) \big( e^{ity} \big) }{ \sqrt{2 \pi} } \, \Bigg|_{-\infty}^{+\infty} - \int\limits_{-\infty}^{+\infty} \left( \frac{ -e^{-y^2 / 2} }{ \sqrt{2 \pi} } \right) e^{ity} (it) \, dy \right]$$
donde el primer sumando es cero dado que $-e^{-y^2 / 2}$ tiende a cero en los límites propuestos, mientras que $e^{ity}$ está acotada, dado que podemos escribirla como una función de senos y cosenos, los cuales están acotados. Por lo tanto, obtenemos que:
$$\frac{ \partial }{ \partial t } \varphi_Y (t) = - i \int\limits_{-\infty}^{+\infty} \left( \frac{ -e^{-y^2 / 2} }{ \sqrt{2 \pi} } \right) e^{ity} (it) \, dy = - t \int\limits_{-\infty}^{+\infty} \left( \frac{ e^{-y^2 / 2} }{ \sqrt{2 \pi} } \right) e^{ity} dy = - t \, \varphi_Y(t)$$

Por lo tanto, hallamos que $\varphi'_Y(t) = - t \varphi_Y (t)$. Esto equivale a resolver la ecuación diferencial lineal de primer orden $\varphi'_Y(t) + t \varphi_Y(t) = 0$. Por lo tanto, tenemos que:
$$\left. \begin{array}{l}
\varphi_Y(t) = c \, e^{-t^2 / 2} \\
\varphi_Y(0) = 1 \Rightarrow c = 1
\end{array} \right\} \Rightarrow \varphi_Y(t) = e^{-t^2 / 2}$$

Aplicando ahora la propiedad 3 (prop 3.3), obtenemos que:
$$\varphi_{X} (t) = \varphi_{\sigma Y + \mu} (t) = e^{it \mu} \varphi_{Y} (t \, \sigma) = e^{it \mu} e^{-(\sigma t)^2 / 2} = \exp\left\{ it \mu - \frac{ (\sigma t)^2 }{2} \right\}$$

\newpage

# Ejercicio 3

$$i \E(X) = \left. \frac{ \partial }{ \partial t } \varphi_X (t) \right|_{t = 0} = \left. \frac{1}{4} \, 2 \, \left( 1 + e^{3it} \right) \left( 3i e^{3it} \right) \right|_{t = 0} = \left. \frac{ 3i }{ 2 } \left( 1 + e^{3it} \right) e^{3it} \right|_{t = 0} =$$
$$= \frac{ 3i }{ 2 } \left( 1 + e^{3i(0)} \right) e^{3i(0)} = \frac{ 3i }{ 2 } (1 + 1) = 3i \Rightarrow \E(X) = 3$$

$$i^2 \E (X^2) = \left. \frac{ \partial^2 }{\partial^2 t } \varphi_X (t) \right|_{t = 0} = \left. \frac{ \partial }{ \partial t} \left[  \frac{ 3i }{ 2 } \left( 1 + e^{3it} \right) e^{3it} \right] \right|_{t = 0} = \left. \frac{3i}{2} \left( 3i e^{3it} e^{3it} + ( 1 + e^{3it} ) 3i e^{3it} \right) \right|_{t = 0} =$$
$$= \left. \frac{ 9 i^2}{2} e^{3it} \left( 2 \, e^{3it} + 1 \right) \right|_{t = 0} = \frac{ 9 i^2}{2} e^{3i(0)} \left( 2 \, e^{3i(0)} + 1 \right) = \frac{ 9 i^2}{2} 3 = \frac{27}{2} i^2 \Rightarrow \E(X^2) = \frac{27}{2} $$

$$\therefore \V(X) = \E(X^2) - {\E}^2(X) = \frac{27}{2} - 3^2 = \frac{27}{2} - 9 = \frac{9}{2}$$

# Ejercicio 4

Queremos hallar una variable aleatoria $Y$ tal que $\varphi_Y(t) = \sum\limits_{j = 1}^{n} a_j \, \varphi_{X_j}(t)$.

$$\varphi_Y(t) = \sum\limits_{j = 1}^{n} a_j \, \varphi_{X_j}(t) = \sum\limits_{j = 1}^{n} a_j \E \big( e^{itX_j} \big) = \sum\limits_{j = 1}^{n} a_j \int\limits_{\mathbb{R}} e^{itx} d F_j(x) = \int\limits_{\mathbb{R}} \sum\limits_{j = 1}^{n} a_j e^{itx} d F_j(x) =$$
$$= \int\limits_{\mathbb{R}} e^{itx} \sum\limits_{j = 1}^{n} a_j d F_j(x) = \int\limits_{\mathbb{R}} e^{itx} d \left( \sum\limits_{j = 1}^{n} a_j F_j(x) \right) = \int\limits_{\mathbb{R}} e^{itx} d F_Y(x) = \E \big( e^{itY} \big) = \varphi_Y(t)$$

Por lo tanto, $Y$ debe ser tal que $Y = \sum\limits_{j = 1}^{n} a_j F_j(x)$. Es decir, una combinación lineal convexa de la variables aleatorias originales.

\newpage

# Ejercicio 5

## Parte a

Sea $X$ una variable aleatoria tal que $X \overset{cs}{=} c$. Entonces:

$$\varphi_X(t) = \E \big( e^{itX} \big) = e^{itc}$$

## Parte b

Sea $X$ una variable aleatoria tal que $X = \left\{ \begin{array}{c c c} -1 & \text{ con probabilidad } & 1/2 \\ 1 & \text{ con probabilidad } & 1/2 \end{array} \right.$

$$\begin{array}{ r c l l}
\varphi_X(t) & = & \E \big( e^{itX}) & \text{definición de función característica} \\ \\
             & = & e^{it(-1)} \frac{1}{2} + e^{it(1)} \frac{1}{2} & \text{definición de esperanza de una va} \\ \\
             & = & \frac{1}{2} \left[ e^{-it} + e^{it} \right] \\ \\
             & = & \frac{1}{2} \Big[ \cos(-t) + i \sin(-t) + \cos(t) + i \sin(t) \Big] & \text{definición de exponencial compleja} \\ \\
             & = & \frac{1}{2} \Big[ 2 \, \cos(t) + i \sin(-t) + i \sin(t) \Big] & \text{coseno es función par} \\ \\
             & = & \frac{1}{2} \Big[ 2 \, \cos(t) - i \sin(t) + i \sin(t) \Big] & \text{seno es función impar} \\ \\
             & = & \frac{1}{2} \Big[ 2 \, \cos(t) \Big] \\ \\
             & = & \cos(t)
\end{array}$$

## Parte c

$\sin(0) = 0 \neq 1 \Rightarrow$ no es una función característica (no cumple propiedad 3.3/2).

\newpage

## Parte d

Sea $Y = X$, donde $X$ es la misma variable aleatoria de la parte b, y $X$ e $Y$ son independientes. Sea $Z = X + Y$ otra variable aleatoria. Luego entonces:

$$\varphi_Z(t) = \varphi_{X + Y}(t) = \varphi_X(t) \, \varphi_Y(t) = \cos(t) \, \cos(t) = \cos^2(t)$$

## Parte e

Primero notemos que:

$$\varphi(t) = \frac{1}{8} \left( e^{it} + e^{2it} \right)^3 = \frac{1}{2^3} \left( e^{it} + e^{2it} \right)^3 = \left[ \frac{1}{2} \left( e^{it} + e^{2it} \right) \right]^3$$

Por lo tanto, estamos buscando tres variables aleatorias independientes e idénticamente distribuidas con función característica:

$$\varphi_{X_j}(t) = \frac{1}{2} \left( e^{it} + e^{2it} \right)$$

Una posible candidata sería:

$$X_j = \left\{ 
\begin{array}{c c c} 
1 & \text{ con probabilidad } & 1/2 \\
2 & \text{ con probabilidad } & 1/2
\end{array} \right.$$

Con la cual, si llamamos $X = \sum\limits_{j = 1}^{3} X_j$, obtendríamos:

$$\varphi_X(t) = \left[ \varphi_{x_j}(t) \right]^3 = \left[ \E \big( e^{itX_j}) \right]^3 = \left[ e^{it(1)} \frac{1}{2} + e^{it(2)} \frac{1}{2} \right]^3 = \left[ \frac{1}{2} \left( e^{it} + e^{2it} \right) \right]^3 = \frac{1}{8} \left( e^{it} + e^{2it} \right)^3 $$
















